export type SkillQuestion = { id: string; image: string; correctIndex: number };
export type Skill = { id: number; title: string; questions: SkillQuestion[] };

export const SKILLS: Skill[] = [
  { id: 1, title: "ترتيب العمليات الحسابية", questions: [
    { id: "sk1_q1", image: "/skill-crops/sk1_q1.jpg", correctIndex: 0 },
    { id: "sk1_q2", image: "/skill-crops/sk1_q2.jpg", correctIndex: 0 },
    { id: "sk1_q3", image: "/skill-crops/sk1_q3.jpg", correctIndex: 0 },
    { id: "sk1_q4", image: "/skill-crops/sk1_q4.jpg", correctIndex: 0 },
    { id: "sk1_q5", image: "/skill-crops/sk1_q5.jpg", correctIndex: 0 },
    { id: "sk1_q6", image: "/skill-crops/sk1_q6.jpg", correctIndex: 0 },
    { id: "sk1_q7", image: "/skill-crops/sk1_q7.jpg", correctIndex: 0 },
    { id: "sk1_q8", image: "/skill-crops/sk1_q8.jpg", correctIndex: 0 },
    { id: "sk1_q9", image: "/skill-crops/sk1_q9.jpg", correctIndex: 0 },
    { id: "sk1_q10", image: "/skill-crops/sk1_q10.jpg", correctIndex: 0 },
    { id: "sk1_q11", image: "/skill-crops/sk1_q11.jpg", correctIndex: 0 },
    { id: "sk1_q12", image: "/skill-crops/sk1_q12.jpg", correctIndex: 0 },
  ] },
  { id: 2, title: "الحساب الذهني", questions: [
    { id: "sk2_q1", image: "/skill-crops/sk2_q1.jpg", correctIndex: 0 },
    { id: "sk2_q2", image: "/skill-crops/sk2_q2.jpg", correctIndex: 0 },
    { id: "sk2_q3", image: "/skill-crops/sk2_q3.jpg", correctIndex: 0 },
    { id: "sk2_q4", image: "/skill-crops/sk2_q4.jpg", correctIndex: 0 },
    { id: "sk2_q5", image: "/skill-crops/sk2_q5.jpg", correctIndex: 0 },
    { id: "sk2_q6", image: "/skill-crops/sk2_q6.jpg", correctIndex: 0 },
    { id: "sk2_q7", image: "/skill-crops/sk2_q7.jpg", correctIndex: 0 },
    { id: "sk2_q8", image: "/skill-crops/sk2_q8.jpg", correctIndex: 0 },
    { id: "sk2_q9", image: "/skill-crops/sk2_q9.jpg", correctIndex: 0 },
    { id: "sk2_q10", image: "/skill-crops/sk2_q10.jpg", correctIndex: 0 },
    { id: "sk2_q11", image: "/skill-crops/sk2_q11.jpg", correctIndex: 0 },
    { id: "sk2_q12", image: "/skill-crops/sk2_q12.jpg", correctIndex: 0 },
    { id: "sk2_q13", image: "/skill-crops/sk2_q13.jpg", correctIndex: 0 },
    { id: "sk2_q14", image: "/skill-crops/sk2_q14.jpg", correctIndex: 0 },
    { id: "sk2_q15", image: "/skill-crops/sk2_q15.jpg", correctIndex: 0 },
  ] },
  { id: 3, title: "الأعداد العشرية", questions: [
    { id: "sk3_q1", image: "/skill-crops/sk3_q1.jpg", correctIndex: 0 },
    { id: "sk3_q2", image: "/skill-crops/sk3_q2.jpg", correctIndex: 0 },
    { id: "sk3_q3", image: "/skill-crops/sk3_q3.jpg", correctIndex: 0 },
    { id: "sk3_q4", image: "/skill-crops/sk3_q4.jpg", correctIndex: 0 },
    { id: "sk3_q5", image: "/skill-crops/sk3_q5.jpg", correctIndex: 0 },
    { id: "sk3_q6", image: "/skill-crops/sk3_q6.jpg", correctIndex: 0 },
    { id: "sk3_q7", image: "/skill-crops/sk3_q7.jpg", correctIndex: 0 },
    { id: "sk3_q8", image: "/skill-crops/sk3_q8.jpg", correctIndex: 0 },
    { id: "sk3_q9", image: "/skill-crops/sk3_q9.jpg", correctIndex: 0 },
    { id: "sk3_q10", image: "/skill-crops/sk3_q10.jpg", correctIndex: 0 },
    { id: "sk3_q11", image: "/skill-crops/sk3_q11.jpg", correctIndex: 0 },
  ] },
  { id: 4, title: "الأسس", questions: [
    { id: "sk4_q1", image: "/skill-crops/sk4_q1.jpg", correctIndex: 0 },
    { id: "sk4_q2", image: "/skill-crops/sk4_q2.jpg", correctIndex: 0 },
    { id: "sk4_q3", image: "/skill-crops/sk4_q3.jpg", correctIndex: 0 },
    { id: "sk4_q4", image: "/skill-crops/sk4_q4.jpg", correctIndex: 0 },
    { id: "sk4_q5", image: "/skill-crops/sk4_q5.jpg", correctIndex: 0 },
    { id: "sk4_q6", image: "/skill-crops/sk4_q6.jpg", correctIndex: 0 },
    { id: "sk4_q7", image: "/skill-crops/sk4_q7.jpg", correctIndex: 0 },
    { id: "sk4_q8", image: "/skill-crops/sk4_q8.jpg", correctIndex: 0 },
    { id: "sk4_q9", image: "/skill-crops/sk4_q9.jpg", correctIndex: 0 },
    { id: "sk4_q10", image: "/skill-crops/sk4_q10.jpg", correctIndex: 0 },
    { id: "sk4_q11", image: "/skill-crops/sk4_q11.jpg", correctIndex: 0 },
    { id: "sk4_q12", image: "/skill-crops/sk4_q12.jpg", correctIndex: 0 },
  ] },
  { id: 5, title: "أشكال فن والأعداد المحصورة", questions: [
    { id: "sk5_q1", image: "/skill-crops/sk5_q1.jpg", correctIndex: 0 },
    { id: "sk5_q2", image: "/skill-crops/sk5_q2.jpg", correctIndex: 0 },
    { id: "sk5_q3", image: "/skill-crops/sk5_q3.jpg", correctIndex: 0 },
    { id: "sk5_q4", image: "/skill-crops/sk5_q4.jpg", correctIndex: 0 },
    { id: "sk5_q5", image: "/skill-crops/sk5_q5.jpg", correctIndex: 0 },
    { id: "sk5_q6", image: "/skill-crops/sk5_q6.jpg", correctIndex: 0 },
    { id: "sk5_q7", image: "/skill-crops/sk5_q7.jpg", correctIndex: 0 },
    { id: "sk5_q8", image: "/skill-crops/sk5_q8.jpg", correctIndex: 0 },
    { id: "sk5_q9", image: "/skill-crops/sk5_q9.jpg", correctIndex: 0 },
    { id: "sk5_q10", image: "/skill-crops/sk5_q10.jpg", correctIndex: 0 },
    { id: "sk5_q11", image: "/skill-crops/sk5_q11.jpg", correctIndex: 0 },
    { id: "sk5_q12", image: "/skill-crops/sk5_q12.jpg", correctIndex: 0 },
    { id: "sk5_q13", image: "/skill-crops/sk5_q13.jpg", correctIndex: 0 },
  ] },
  { id: 6, title: "الكسور الاعتيادية", questions: [
    { id: "sk6_q1", image: "/skill-crops/sk6_q1.jpg", correctIndex: 0 },
    { id: "sk6_q2", image: "/skill-crops/sk6_q2.jpg", correctIndex: 0 },
    { id: "sk6_q3", image: "/skill-crops/sk6_q3.jpg", correctIndex: 0 },
    { id: "sk6_q4", image: "/skill-crops/sk6_q4.jpg", correctIndex: 0 },
    { id: "sk6_q5", image: "/skill-crops/sk6_q5.jpg", correctIndex: 0 },
    { id: "sk6_q6", image: "/skill-crops/sk6_q6.jpg", correctIndex: 0 },
    { id: "sk6_q7", image: "/skill-crops/sk6_q7.jpg", correctIndex: 0 },
    { id: "sk6_q8", image: "/skill-crops/sk6_q8.jpg", correctIndex: 0 },
    { id: "sk6_q9", image: "/skill-crops/sk6_q9.jpg", correctIndex: 0 },
    { id: "sk6_q10", image: "/skill-crops/sk6_q10.jpg", correctIndex: 0 },
    { id: "sk6_q11", image: "/skill-crops/sk6_q11.jpg", correctIndex: 0 },
    { id: "sk6_q12", image: "/skill-crops/sk6_q12.jpg", correctIndex: 0 },
    { id: "sk6_q13", image: "/skill-crops/sk6_q13.jpg", correctIndex: 0 },
    { id: "sk6_q14", image: "/skill-crops/sk6_q14.jpg", correctIndex: 0 },
    { id: "sk6_q15", image: "/skill-crops/sk6_q15.jpg", correctIndex: 0 },
    { id: "sk6_q16", image: "/skill-crops/sk6_q16.jpg", correctIndex: 0 },
  ] },
  { id: 7, title: "قابلية القسمة على الأعداد", questions: [
    { id: "sk7_q1", image: "/skill-crops/sk7_q1.jpg", correctIndex: 0 },
    { id: "sk7_q2", image: "/skill-crops/sk7_q2.jpg", correctIndex: 0 },
    { id: "sk7_q3", image: "/skill-crops/sk7_q3.jpg", correctIndex: 0 },
    { id: "sk7_q4", image: "/skill-crops/sk7_q4.jpg", correctIndex: 0 },
    { id: "sk7_q5", image: "/skill-crops/sk7_q5.jpg", correctIndex: 0 },
    { id: "sk7_q6", image: "/skill-crops/sk7_q6.jpg", correctIndex: 0 },
    { id: "sk7_q7", image: "/skill-crops/sk7_q7.jpg", correctIndex: 0 },
    { id: "sk7_q8", image: "/skill-crops/sk7_q8.jpg", correctIndex: 0 },
    { id: "sk7_q9", image: "/skill-crops/sk7_q9.jpg", correctIndex: 0 },
    { id: "sk7_q10", image: "/skill-crops/sk7_q10.jpg", correctIndex: 0 },
    { id: "sk7_q11", image: "/skill-crops/sk7_q11.jpg", correctIndex: 0 },
    { id: "sk7_q12", image: "/skill-crops/sk7_q12.jpg", correctIndex: 0 },
  ] },
  { id: 8, title: "أنواع الزوايا", questions: [
    { id: "sk8_q1", image: "/skill-crops/sk8_q1.jpg", correctIndex: 0 },
    { id: "sk8_q2", image: "/skill-crops/sk8_q2.jpg", correctIndex: 0 },
    { id: "sk8_q3", image: "/skill-crops/sk8_q3.jpg", correctIndex: 0 },
    { id: "sk8_q4", image: "/skill-crops/sk8_q4.jpg", correctIndex: 0 },
    { id: "sk8_q5", image: "/skill-crops/sk8_q5.jpg", correctIndex: 0 },
    { id: "sk8_q6", image: "/skill-crops/sk8_q6.jpg", correctIndex: 0 },
    { id: "sk8_q7", image: "/skill-crops/sk8_q7.jpg", correctIndex: 0 },
    { id: "sk8_q8", image: "/skill-crops/sk8_q8.jpg", correctIndex: 0 },
    { id: "sk8_q9", image: "/skill-crops/sk8_q9.jpg", correctIndex: 0 },
    { id: "sk8_q10", image: "/skill-crops/sk8_q10.jpg", correctIndex: 0 },
    { id: "sk8_q11", image: "/skill-crops/sk8_q11.jpg", correctIndex: 0 },
    { id: "sk8_q12", image: "/skill-crops/sk8_q12.jpg", correctIndex: 0 },
  ] },
  { id: 9, title: "الدوريات والأنماط", questions: [
    { id: "sk9_q1", image: "/skill-crops/sk9_q1.jpg", correctIndex: 0 },
    { id: "sk9_q2", image: "/skill-crops/sk9_q2.jpg", correctIndex: 0 },
    { id: "sk9_q3", image: "/skill-crops/sk9_q3.jpg", correctIndex: 0 },
    { id: "sk9_q4", image: "/skill-crops/sk9_q4.jpg", correctIndex: 0 },
    { id: "sk9_q5", image: "/skill-crops/sk9_q5.jpg", correctIndex: 0 },
    { id: "sk9_q6", image: "/skill-crops/sk9_q6.jpg", correctIndex: 0 },
    { id: "sk9_q7", image: "/skill-crops/sk9_q7.jpg", correctIndex: 0 },
    { id: "sk9_q8", image: "/skill-crops/sk9_q8.jpg", correctIndex: 0 },
    { id: "sk9_q9", image: "/skill-crops/sk9_q9.jpg", correctIndex: 0 },
    { id: "sk9_q10", image: "/skill-crops/sk9_q10.jpg", correctIndex: 0 },
    { id: "sk9_q11", image: "/skill-crops/sk9_q11.jpg", correctIndex: 0 },
    { id: "sk9_q12", image: "/skill-crops/sk9_q12.jpg", correctIndex: 0 },
  ] },
  { id: 10, title: "المثلثات", questions: [
    { id: "sk10_q1", image: "/skill-crops/sk10_q1.jpg", correctIndex: 0 },
    { id: "sk10_q2", image: "/skill-crops/sk10_q2.jpg", correctIndex: 0 },
    { id: "sk10_q3", image: "/skill-crops/sk10_q3.jpg", correctIndex: 0 },
    { id: "sk10_q4", image: "/skill-crops/sk10_q4.jpg", correctIndex: 0 },
    { id: "sk10_q5", image: "/skill-crops/sk10_q5.jpg", correctIndex: 0 },
    { id: "sk10_q6", image: "/skill-crops/sk10_q6.jpg", correctIndex: 0 },
    { id: "sk10_q7", image: "/skill-crops/sk10_q7.jpg", correctIndex: 0 },
    { id: "sk10_q8", image: "/skill-crops/sk10_q8.jpg", correctIndex: 0 },
    { id: "sk10_q9", image: "/skill-crops/sk10_q9.jpg", correctIndex: 0 },
    { id: "sk10_q10", image: "/skill-crops/sk10_q10.jpg", correctIndex: 0 },
    { id: "sk10_q11", image: "/skill-crops/sk10_q11.jpg", correctIndex: 0 },
    { id: "sk10_q12", image: "/skill-crops/sk10_q12.jpg", correctIndex: 0 },
  ] },
  { id: 11, title: "عدد المستطيلات والمربعات والمثلثات", questions: [
    { id: "sk11_q1", image: "/skill-crops/sk11_q1.jpg", correctIndex: 0 },
    { id: "sk11_q2", image: "/skill-crops/sk11_q2.jpg", correctIndex: 0 },
    { id: "sk11_q3", image: "/skill-crops/sk11_q3.jpg", correctIndex: 0 },
    { id: "sk11_q4", image: "/skill-crops/sk11_q4.jpg", correctIndex: 0 },
    { id: "sk11_q5", image: "/skill-crops/sk11_q5.jpg", correctIndex: 0 },
    { id: "sk11_q6", image: "/skill-crops/sk11_q6.jpg", correctIndex: 0 },
    { id: "sk11_q7", image: "/skill-crops/sk11_q7.jpg", correctIndex: 0 },
    { id: "sk11_q8", image: "/skill-crops/sk11_q8.jpg", correctIndex: 0 },
    { id: "sk11_q9", image: "/skill-crops/sk11_q9.jpg", correctIndex: 0 },
    { id: "sk11_q10", image: "/skill-crops/sk11_q10.jpg", correctIndex: 0 },
    { id: "sk11_q11", image: "/skill-crops/sk11_q11.jpg", correctIndex: 0 },
    { id: "sk11_q12", image: "/skill-crops/sk11_q12.jpg", correctIndex: 0 },
  ] },
  { id: 12, title: "المتوسط والوسيط والمنوال", questions: [
    { id: "sk12_q1", image: "/skill-crops/sk12_q1.jpg", correctIndex: 0 },
    { id: "sk12_q2", image: "/skill-crops/sk12_q2.jpg", correctIndex: 0 },
    { id: "sk12_q3", image: "/skill-crops/sk12_q3.jpg", correctIndex: 0 },
    { id: "sk12_q4", image: "/skill-crops/sk12_q4.jpg", correctIndex: 0 },
    { id: "sk12_q5", image: "/skill-crops/sk12_q5.jpg", correctIndex: 0 },
    { id: "sk12_q6", image: "/skill-crops/sk12_q6.jpg", correctIndex: 0 },
    { id: "sk12_q7", image: "/skill-crops/sk12_q7.jpg", correctIndex: 0 },
    { id: "sk12_q8", image: "/skill-crops/sk12_q8.jpg", correctIndex: 0 },
    { id: "sk12_q9", image: "/skill-crops/sk12_q9.jpg", correctIndex: 0 },
    { id: "sk12_q10", image: "/skill-crops/sk12_q10.jpg", correctIndex: 0 },
    { id: "sk12_q11", image: "/skill-crops/sk12_q11.jpg", correctIndex: 0 },
    { id: "sk12_q12", image: "/skill-crops/sk12_q12.jpg", correctIndex: 0 },
  ] },
  { id: 13, title: "المعادلات", questions: [
    { id: "sk13_q1", image: "/skill-crops/sk13_q1.jpg", correctIndex: 0 },
    { id: "sk13_q2", image: "/skill-crops/sk13_q2.jpg", correctIndex: 0 },
    { id: "sk13_q3", image: "/skill-crops/sk13_q3.jpg", correctIndex: 0 },
    { id: "sk13_q4", image: "/skill-crops/sk13_q4.jpg", correctIndex: 0 },
    { id: "sk13_q5", image: "/skill-crops/sk13_q5.jpg", correctIndex: 0 },
    { id: "sk13_q6", image: "/skill-crops/sk13_q6.jpg", correctIndex: 0 },
    { id: "sk13_q7", image: "/skill-crops/sk13_q7.jpg", correctIndex: 0 },
    { id: "sk13_q8", image: "/skill-crops/sk13_q8.jpg", correctIndex: 0 },
    { id: "sk13_q9", image: "/skill-crops/sk13_q9.jpg", correctIndex: 0 },
    { id: "sk13_q10", image: "/skill-crops/sk13_q10.jpg", correctIndex: 0 },
    { id: "sk13_q11", image: "/skill-crops/sk13_q11.jpg", correctIndex: 0 },
    { id: "sk13_q12", image: "/skill-crops/sk13_q12.jpg", correctIndex: 0 },
  ] },
  { id: 14, title: "التوازي", questions: [
    { id: "sk14_q1", image: "/skill-crops/sk14_q1.jpg", correctIndex: 0 },
    { id: "sk14_q2", image: "/skill-crops/sk14_q2.jpg", correctIndex: 0 },
    { id: "sk14_q3", image: "/skill-crops/sk14_q3.jpg", correctIndex: 0 },
    { id: "sk14_q4", image: "/skill-crops/sk14_q4.jpg", correctIndex: 0 },
    { id: "sk14_q5", image: "/skill-crops/sk14_q5.jpg", correctIndex: 0 },
    { id: "sk14_q6", image: "/skill-crops/sk14_q6.jpg", correctIndex: 0 },
    { id: "sk14_q7", image: "/skill-crops/sk14_q7.jpg", correctIndex: 0 },
    { id: "sk14_q8", image: "/skill-crops/sk14_q8.jpg", correctIndex: 0 },
    { id: "sk14_q9", image: "/skill-crops/sk14_q9.jpg", correctIndex: 0 },
    { id: "sk14_q10", image: "/skill-crops/sk14_q10.jpg", correctIndex: 0 },
    { id: "sk14_q11", image: "/skill-crops/sk14_q11.jpg", correctIndex: 0 },
    { id: "sk14_q12", image: "/skill-crops/sk14_q12.jpg", correctIndex: 0 },
  ] },
  { id: 15, title: "السرعة والمسافة والزمن", questions: [
    { id: "sk15_q1", image: "/skill-crops/sk15_q1.jpg", correctIndex: 0 },
    { id: "sk15_q2", image: "/skill-crops/sk15_q2.jpg", correctIndex: 0 },
    { id: "sk15_q3", image: "/skill-crops/sk15_q3.jpg", correctIndex: 0 },
    { id: "sk15_q4", image: "/skill-crops/sk15_q4.jpg", correctIndex: 0 },
    { id: "sk15_q5", image: "/skill-crops/sk15_q5.jpg", correctIndex: 0 },
    { id: "sk15_q6", image: "/skill-crops/sk15_q6.jpg", correctIndex: 0 },
    { id: "sk15_q7", image: "/skill-crops/sk15_q7.jpg", correctIndex: 0 },
    { id: "sk15_q8", image: "/skill-crops/sk15_q8.jpg", correctIndex: 0 },
    { id: "sk15_q9", image: "/skill-crops/sk15_q9.jpg", correctIndex: 0 },
    { id: "sk15_q10", image: "/skill-crops/sk15_q10.jpg", correctIndex: 0 },
    { id: "sk15_q11", image: "/skill-crops/sk15_q11.jpg", correctIndex: 0 },
    { id: "sk15_q12", image: "/skill-crops/sk15_q12.jpg", correctIndex: 0 },
  ] },
  { id: 16, title: "المستطيل", questions: [
    { id: "sk16_q1", image: "/skill-crops/sk16_q1.jpg", correctIndex: 0 },
    { id: "sk16_q2", image: "/skill-crops/sk16_q2.jpg", correctIndex: 0 },
    { id: "sk16_q3", image: "/skill-crops/sk16_q3.jpg", correctIndex: 0 },
    { id: "sk16_q4", image: "/skill-crops/sk16_q4.jpg", correctIndex: 0 },
    { id: "sk16_q5", image: "/skill-crops/sk16_q5.jpg", correctIndex: 0 },
    { id: "sk16_q6", image: "/skill-crops/sk16_q6.jpg", correctIndex: 0 },
    { id: "sk16_q7", image: "/skill-crops/sk16_q7.jpg", correctIndex: 0 },
    { id: "sk16_q8", image: "/skill-crops/sk16_q8.jpg", correctIndex: 0 },
    { id: "sk16_q9", image: "/skill-crops/sk16_q9.jpg", correctIndex: 0 },
    { id: "sk16_q10", image: "/skill-crops/sk16_q10.jpg", correctIndex: 0 },
    { id: "sk16_q11", image: "/skill-crops/sk16_q11.jpg", correctIndex: 0 },
    { id: "sk16_q12", image: "/skill-crops/sk16_q12.jpg", correctIndex: 0 },
  ] },
  { id: 17, title: "المتطابقات", questions: [
    { id: "sk17_q1", image: "/skill-crops/sk17_q1.jpg", correctIndex: 0 },
    { id: "sk17_q2", image: "/skill-crops/sk17_q2.jpg", correctIndex: 0 },
    { id: "sk17_q3", image: "/skill-crops/sk17_q3.jpg", correctIndex: 0 },
    { id: "sk17_q4", image: "/skill-crops/sk17_q4.jpg", correctIndex: 0 },
    { id: "sk17_q5", image: "/skill-crops/sk17_q5.jpg", correctIndex: 0 },
    { id: "sk17_q6", image: "/skill-crops/sk17_q6.jpg", correctIndex: 0 },
    { id: "sk17_q7", image: "/skill-crops/sk17_q7.jpg", correctIndex: 0 },
    { id: "sk17_q8", image: "/skill-crops/sk17_q8.jpg", correctIndex: 0 },
    { id: "sk17_q9", image: "/skill-crops/sk17_q9.jpg", correctIndex: 0 },
    { id: "sk17_q10", image: "/skill-crops/sk17_q10.jpg", correctIndex: 0 },
    { id: "sk17_q11", image: "/skill-crops/sk17_q11.jpg", correctIndex: 0 },
    { id: "sk17_q12", image: "/skill-crops/sk17_q12.jpg", correctIndex: 0 },
    { id: "sk17_q13", image: "/skill-crops/sk17_q13.jpg", correctIndex: 0 },
  ] },
  { id: 18, title: "المربع", questions: [
    { id: "sk18_q1", image: "/skill-crops/sk18_q1.jpg", correctIndex: 0 },
    { id: "sk18_q2", image: "/skill-crops/sk18_q2.jpg", correctIndex: 0 },
    { id: "sk18_q3", image: "/skill-crops/sk18_q3.jpg", correctIndex: 0 },
    { id: "sk18_q4", image: "/skill-crops/sk18_q4.jpg", correctIndex: 0 },
    { id: "sk18_q5", image: "/skill-crops/sk18_q5.jpg", correctIndex: 0 },
    { id: "sk18_q6", image: "/skill-crops/sk18_q6.jpg", correctIndex: 0 },
    { id: "sk18_q7", image: "/skill-crops/sk18_q7.jpg", correctIndex: 0 },
    { id: "sk18_q8", image: "/skill-crops/sk18_q8.jpg", correctIndex: 0 },
    { id: "sk18_q9", image: "/skill-crops/sk18_q9.jpg", correctIndex: 0 },
    { id: "sk18_q10", image: "/skill-crops/sk18_q10.jpg", correctIndex: 0 },
    { id: "sk18_q11", image: "/skill-crops/sk18_q11.jpg", correctIndex: 0 },
    { id: "sk18_q12", image: "/skill-crops/sk18_q12.jpg", correctIndex: 0 },
    { id: "sk18_q13", image: "/skill-crops/sk18_q13.jpg", correctIndex: 0 },
  ] },
  { id: 19, title: "الأعمار والأوراق النقدية", questions: [
    { id: "sk19_q1", image: "/skill-crops/sk19_q1.jpg", correctIndex: 0 },
    { id: "sk19_q2", image: "/skill-crops/sk19_q2.jpg", correctIndex: 0 },
    { id: "sk19_q3", image: "/skill-crops/sk19_q3.jpg", correctIndex: 0 },
    { id: "sk19_q4", image: "/skill-crops/sk19_q4.jpg", correctIndex: 0 },
    { id: "sk19_q5", image: "/skill-crops/sk19_q5.jpg", correctIndex: 0 },
    { id: "sk19_q6", image: "/skill-crops/sk19_q6.jpg", correctIndex: 0 },
    { id: "sk19_q7", image: "/skill-crops/sk19_q7.jpg", correctIndex: 0 },
    { id: "sk19_q8", image: "/skill-crops/sk19_q8.jpg", correctIndex: 0 },
    { id: "sk19_q9", image: "/skill-crops/sk19_q9.jpg", correctIndex: 0 },
    { id: "sk19_q10", image: "/skill-crops/sk19_q10.jpg", correctIndex: 0 },
    { id: "sk19_q11", image: "/skill-crops/sk19_q11.jpg", correctIndex: 0 },
    { id: "sk19_q12", image: "/skill-crops/sk19_q12.jpg", correctIndex: 0 },
    { id: "sk19_q13", image: "/skill-crops/sk19_q13.jpg", correctIndex: 0 },
    { id: "sk19_q14", image: "/skill-crops/sk19_q14.jpg", correctIndex: 0 },
    { id: "sk19_q15", image: "/skill-crops/sk19_q15.jpg", correctIndex: 0 },
  ] },
  { id: 20, title: "الجذور", questions: [
    { id: "sk20_q1", image: "/skill-crops/sk20_q1.jpg", correctIndex: 0 },
    { id: "sk20_q2", image: "/skill-crops/sk20_q2.jpg", correctIndex: 0 },
    { id: "sk20_q3", image: "/skill-crops/sk20_q3.jpg", correctIndex: 0 },
    { id: "sk20_q4", image: "/skill-crops/sk20_q4.jpg", correctIndex: 0 },
    { id: "sk20_q5", image: "/skill-crops/sk20_q5.jpg", correctIndex: 0 },
    { id: "sk20_q6", image: "/skill-crops/sk20_q6.jpg", correctIndex: 0 },
    { id: "sk20_q7", image: "/skill-crops/sk20_q7.jpg", correctIndex: 0 },
    { id: "sk20_q8", image: "/skill-crops/sk20_q8.jpg", correctIndex: 0 },
    { id: "sk20_q9", image: "/skill-crops/sk20_q9.jpg", correctIndex: 0 },
    { id: "sk20_q10", image: "/skill-crops/sk20_q10.jpg", correctIndex: 0 },
    { id: "sk20_q11", image: "/skill-crops/sk20_q11.jpg", correctIndex: 0 },
    { id: "sk20_q12", image: "/skill-crops/sk20_q12.jpg", correctIndex: 0 },
  ] },
  { id: 21, title: "الرسوم البيانية", questions: [
    { id: "sk21_q1", image: "/skill-crops/sk21_q1.jpg", correctIndex: 0 },
    { id: "sk21_q2", image: "/skill-crops/sk21_q2.jpg", correctIndex: 0 },
    { id: "sk21_q3", image: "/skill-crops/sk21_q3.jpg", correctIndex: 0 },
    { id: "sk21_q4", image: "/skill-crops/sk21_q4.jpg", correctIndex: 0 },
    { id: "sk21_q5", image: "/skill-crops/sk21_q5.jpg", correctIndex: 0 },
    { id: "sk21_q6", image: "/skill-crops/sk21_q6.jpg", correctIndex: 0 },
    { id: "sk21_q7", image: "/skill-crops/sk21_q7.jpg", correctIndex: 0 },
    { id: "sk21_q8", image: "/skill-crops/sk21_q8.jpg", correctIndex: 0 },
    { id: "sk21_q9", image: "/skill-crops/sk21_q9.jpg", correctIndex: 0 },
    { id: "sk21_q10", image: "/skill-crops/sk21_q10.jpg", correctIndex: 0 },
    { id: "sk21_q11", image: "/skill-crops/sk21_q11.jpg", correctIndex: 0 },
    { id: "sk21_q12", image: "/skill-crops/sk21_q12.jpg", correctIndex: 0 },
  ] },
  { id: 22, title: "المسائل اللفظية وزكاة المال", questions: [
    { id: "sk22_q1", image: "/skill-crops/sk22_q1.jpg", correctIndex: 0 },
    { id: "sk22_q2", image: "/skill-crops/sk22_q2.jpg", correctIndex: 0 },
    { id: "sk22_q3", image: "/skill-crops/sk22_q3.jpg", correctIndex: 0 },
    { id: "sk22_q4", image: "/skill-crops/sk22_q4.jpg", correctIndex: 0 },
    { id: "sk22_q5", image: "/skill-crops/sk22_q5.jpg", correctIndex: 0 },
    { id: "sk22_q6", image: "/skill-crops/sk22_q6.jpg", correctIndex: 0 },
    { id: "sk22_q7", image: "/skill-crops/sk22_q7.jpg", correctIndex: 0 },
    { id: "sk22_q8", image: "/skill-crops/sk22_q8.jpg", correctIndex: 0 },
    { id: "sk22_q9", image: "/skill-crops/sk22_q9.jpg", correctIndex: 0 },
    { id: "sk22_q10", image: "/skill-crops/sk22_q10.jpg", correctIndex: 0 },
    { id: "sk22_q11", image: "/skill-crops/sk22_q11.jpg", correctIndex: 0 },
    { id: "sk22_q12", image: "/skill-crops/sk22_q12.jpg", correctIndex: 0 },
    { id: "sk22_q13", image: "/skill-crops/sk22_q13.jpg", correctIndex: 0 },
    { id: "sk22_q14", image: "/skill-crops/sk22_q14.jpg", correctIndex: 0 },
    { id: "sk22_q15", image: "/skill-crops/sk22_q15.jpg", correctIndex: 0 },
  ] },
  { id: 23, title: "المعين والمتوازي", questions: [
    { id: "sk23_q1", image: "/skill-crops/sk23_q1.jpg", correctIndex: 0 },
    { id: "sk23_q2", image: "/skill-crops/sk23_q2.jpg", correctIndex: 0 },
    { id: "sk23_q3", image: "/skill-crops/sk23_q3.jpg", correctIndex: 0 },
    { id: "sk23_q4", image: "/skill-crops/sk23_q4.jpg", correctIndex: 0 },
    { id: "sk23_q5", image: "/skill-crops/sk23_q5.jpg", correctIndex: 0 },
    { id: "sk23_q6", image: "/skill-crops/sk23_q6.jpg", correctIndex: 0 },
    { id: "sk23_q7", image: "/skill-crops/sk23_q7.jpg", correctIndex: 0 },
    { id: "sk23_q8", image: "/skill-crops/sk23_q8.jpg", correctIndex: 0 },
    { id: "sk23_q9", image: "/skill-crops/sk23_q9.jpg", correctIndex: 0 },
    { id: "sk23_q10", image: "/skill-crops/sk23_q10.jpg", correctIndex: 0 },
    { id: "sk23_q11", image: "/skill-crops/sk23_q11.jpg", correctIndex: 0 },
    { id: "sk23_q12", image: "/skill-crops/sk23_q12.jpg", correctIndex: 0 },
  ] },
  { id: 24, title: "استبدال المتغيرات", questions: [
    { id: "sk24_q1", image: "/skill-crops/sk24_q1.jpg", correctIndex: 0 },
    { id: "sk24_q2", image: "/skill-crops/sk24_q2.jpg", correctIndex: 0 },
    { id: "sk24_q3", image: "/skill-crops/sk24_q3.jpg", correctIndex: 0 },
    { id: "sk24_q4", image: "/skill-crops/sk24_q4.jpg", correctIndex: 0 },
    { id: "sk24_q5", image: "/skill-crops/sk24_q5.jpg", correctIndex: 0 },
    { id: "sk24_q6", image: "/skill-crops/sk24_q6.jpg", correctIndex: 0 },
    { id: "sk24_q7", image: "/skill-crops/sk24_q7.jpg", correctIndex: 0 },
    { id: "sk24_q8", image: "/skill-crops/sk24_q8.jpg", correctIndex: 0 },
    { id: "sk24_q9", image: "/skill-crops/sk24_q9.jpg", correctIndex: 0 },
    { id: "sk24_q10", image: "/skill-crops/sk24_q10.jpg", correctIndex: 0 },
    { id: "sk24_q11", image: "/skill-crops/sk24_q11.jpg", correctIndex: 0 },
    { id: "sk24_q12", image: "/skill-crops/sk24_q12.jpg", correctIndex: 0 },
  ] },
  { id: 25, title: "الدائرة", questions: [
    { id: "sk25_q1", image: "/skill-crops/sk25_q1.jpg", correctIndex: 0 },
    { id: "sk25_q2", image: "/skill-crops/sk25_q2.jpg", correctIndex: 0 },
    { id: "sk25_q3", image: "/skill-crops/sk25_q3.jpg", correctIndex: 0 },
    { id: "sk25_q4", image: "/skill-crops/sk25_q4.jpg", correctIndex: 0 },
    { id: "sk25_q5", image: "/skill-crops/sk25_q5.jpg", correctIndex: 0 },
    { id: "sk25_q6", image: "/skill-crops/sk25_q6.jpg", correctIndex: 0 },
    { id: "sk25_q7", image: "/skill-crops/sk25_q7.jpg", correctIndex: 0 },
    { id: "sk25_q8", image: "/skill-crops/sk25_q8.jpg", correctIndex: 0 },
    { id: "sk25_q9", image: "/skill-crops/sk25_q9.jpg", correctIndex: 0 },
    { id: "sk25_q10", image: "/skill-crops/sk25_q10.jpg", correctIndex: 0 },
    { id: "sk25_q11", image: "/skill-crops/sk25_q11.jpg", correctIndex: 0 },
    { id: "sk25_q12", image: "/skill-crops/sk25_q12.jpg", correctIndex: 0 },
    { id: "sk25_q13", image: "/skill-crops/sk25_q13.jpg", correctIndex: 0 },
    { id: "sk25_q14", image: "/skill-crops/sk25_q14.jpg", correctIndex: 0 },
  ] },
  { id: 26, title: "المساحات المظللة", questions: [
    { id: "sk26_q1", image: "/skill-crops/sk26_q1.jpg", correctIndex: 0 },
    { id: "sk26_q2", image: "/skill-crops/sk26_q2.jpg", correctIndex: 0 },
    { id: "sk26_q3", image: "/skill-crops/sk26_q3.jpg", correctIndex: 0 },
    { id: "sk26_q4", image: "/skill-crops/sk26_q4.jpg", correctIndex: 0 },
    { id: "sk26_q5", image: "/skill-crops/sk26_q5.jpg", correctIndex: 0 },
    { id: "sk26_q6", image: "/skill-crops/sk26_q6.jpg", correctIndex: 0 },
    { id: "sk26_q7", image: "/skill-crops/sk26_q7.jpg", correctIndex: 0 },
    { id: "sk26_q8", image: "/skill-crops/sk26_q8.jpg", correctIndex: 0 },
    { id: "sk26_q9", image: "/skill-crops/sk26_q9.jpg", correctIndex: 0 },
    { id: "sk26_q10", image: "/skill-crops/sk26_q10.jpg", correctIndex: 0 },
    { id: "sk26_q11", image: "/skill-crops/sk26_q11.jpg", correctIndex: 0 },
    { id: "sk26_q12", image: "/skill-crops/sk26_q12.jpg", correctIndex: 0 },
  ] },
  { id: 27, title: "النسبة والتناسب", questions: [
    { id: "sk27_q1", image: "/skill-crops/sk27_q1.jpg", correctIndex: 0 },
    { id: "sk27_q2", image: "/skill-crops/sk27_q2.jpg", correctIndex: 0 },
    { id: "sk27_q3", image: "/skill-crops/sk27_q3.jpg", correctIndex: 0 },
    { id: "sk27_q4", image: "/skill-crops/sk27_q4.jpg", correctIndex: 0 },
    { id: "sk27_q5", image: "/skill-crops/sk27_q5.jpg", correctIndex: 0 },
    { id: "sk27_q6", image: "/skill-crops/sk27_q6.jpg", correctIndex: 0 },
    { id: "sk27_q7", image: "/skill-crops/sk27_q7.jpg", correctIndex: 0 },
    { id: "sk27_q8", image: "/skill-crops/sk27_q8.jpg", correctIndex: 0 },
    { id: "sk27_q9", image: "/skill-crops/sk27_q9.jpg", correctIndex: 0 },
    { id: "sk27_q10", image: "/skill-crops/sk27_q10.jpg", correctIndex: 0 },
    { id: "sk27_q11", image: "/skill-crops/sk27_q11.jpg", correctIndex: 0 },
    { id: "sk27_q12", image: "/skill-crops/sk27_q12.jpg", correctIndex: 0 },
  ] },
  { id: 28, title: "المجسمات", questions: [
    { id: "sk28_q1", image: "/skill-crops/sk28_q1.jpg", correctIndex: 0 },
    { id: "sk28_q2", image: "/skill-crops/sk28_q2.jpg", correctIndex: 0 },
    { id: "sk28_q3", image: "/skill-crops/sk28_q3.jpg", correctIndex: 0 },
    { id: "sk28_q4", image: "/skill-crops/sk28_q4.jpg", correctIndex: 0 },
    { id: "sk28_q5", image: "/skill-crops/sk28_q5.jpg", correctIndex: 0 },
    { id: "sk28_q6", image: "/skill-crops/sk28_q6.jpg", correctIndex: 0 },
    { id: "sk28_q7", image: "/skill-crops/sk28_q7.jpg", correctIndex: 0 },
    { id: "sk28_q8", image: "/skill-crops/sk28_q8.jpg", correctIndex: 0 },
    { id: "sk28_q9", image: "/skill-crops/sk28_q9.jpg", correctIndex: 0 },
    { id: "sk28_q10", image: "/skill-crops/sk28_q10.jpg", correctIndex: 0 },
    { id: "sk28_q11", image: "/skill-crops/sk28_q11.jpg", correctIndex: 0 },
    { id: "sk28_q12", image: "/skill-crops/sk28_q12.jpg", correctIndex: 0 },
    { id: "sk28_q13", image: "/skill-crops/sk28_q13.jpg", correctIndex: 0 },
    { id: "sk28_q14", image: "/skill-crops/sk28_q14.jpg", correctIndex: 0 },
    { id: "sk28_q15", image: "/skill-crops/sk28_q15.jpg", correctIndex: 0 },
  ] },
  { id: 29, title: "المثلثان المتشابهان", questions: [
    { id: "sk29_q1", image: "/skill-crops/sk29_q1.jpg", correctIndex: 0 },
    { id: "sk29_q2", image: "/skill-crops/sk29_q2.jpg", correctIndex: 0 },
    { id: "sk29_q3", image: "/skill-crops/sk29_q3.jpg", correctIndex: 0 },
    { id: "sk29_q4", image: "/skill-crops/sk29_q4.jpg", correctIndex: 0 },
    { id: "sk29_q5", image: "/skill-crops/sk29_q5.jpg", correctIndex: 0 },
    { id: "sk29_q6", image: "/skill-crops/sk29_q6.jpg", correctIndex: 0 },
    { id: "sk29_q7", image: "/skill-crops/sk29_q7.jpg", correctIndex: 0 },
    { id: "sk29_q8", image: "/skill-crops/sk29_q8.jpg", correctIndex: 0 },
    { id: "sk29_q9", image: "/skill-crops/sk29_q9.jpg", correctIndex: 0 },
    { id: "sk29_q10", image: "/skill-crops/sk29_q10.jpg", correctIndex: 0 },
    { id: "sk29_q11", image: "/skill-crops/sk29_q11.jpg", correctIndex: 0 },
    { id: "sk29_q12", image: "/skill-crops/sk29_q12.jpg", correctIndex: 0 },
  ] },
  { id: 30, title: "إتقان الكمي", questions: [
    { id: "sk30_q1", image: "/skill-crops/sk30_q1.jpg", correctIndex: 0 },
    { id: "sk30_q2", image: "/skill-crops/sk30_q2.jpg", correctIndex: 0 },
    { id: "sk30_q3", image: "/skill-crops/sk30_q3.jpg", correctIndex: 0 },
    { id: "sk30_q4", image: "/skill-crops/sk30_q4.jpg", correctIndex: 0 },
    { id: "sk30_q5", image: "/skill-crops/sk30_q5.jpg", correctIndex: 0 },
    { id: "sk30_q6", image: "/skill-crops/sk30_q6.jpg", correctIndex: 0 },
    { id: "sk30_q7", image: "/skill-crops/sk30_q7.jpg", correctIndex: 0 },
    { id: "sk30_q8", image: "/skill-crops/sk30_q8.jpg", correctIndex: 0 },
    { id: "sk30_q9", image: "/skill-crops/sk30_q9.jpg", correctIndex: 0 },
    { id: "sk30_q10", image: "/skill-crops/sk30_q10.jpg", correctIndex: 0 },
    { id: "sk30_q11", image: "/skill-crops/sk30_q11.jpg", correctIndex: 0 },
    { id: "sk30_q12", image: "/skill-crops/sk30_q12.jpg", correctIndex: 0 },
    { id: "sk30_q13", image: "/skill-crops/sk30_q13.jpg", correctIndex: 0 },
  ] },
];

export const SKILL_SECONDS_PER_QUESTION = 60;
export const SKILL_RESULTS_KEY = "nemr:results:skills";
