// Auto-generated from "تأسيس قدرات كمي" — 30 مهارة (فرع). Images live in /skills/.
export type SkillQuestion = { id: string; imageUrl: string; text?: string; choices: string[]; correctIndex: number | null };
export type Skill = { id: number; title: string; questions: SkillQuestion[] };

export const SKILLS: Skill[] = [
  { id: 1, title: "ترتيب العمليات الحسابية", questions: [
    { id: "sk1_q1", imageUrl: "/skills/sk01_p003_01.jpg", text: "$5(120 - 20) + 3 \\times 100 =$", choices: ["$700$", "$1500$", "$800$", "$400$"], correctIndex: null },
    { id: "sk1_q2", imageUrl: "/skills/sk01_p003_02.jpg", text: "$3 + 2 \\times 4 \\div 2 =$", choices: ["$5.5$", "$5$", "$7$", "$10$"], correctIndex: null },
    { id: "sk1_q3", imageUrl: "/skills/sk01_p003_03.jpg", text: "$40 \\div 5 + 3 \\times 2 =$", choices: ["$22$", "$14$", "$10$", "$11$"], correctIndex: null },
    { id: "sk1_q4", imageUrl: "/skills/sk01_p003_04.jpg", text: "$6 - (7 - 1) \\times 4 =$", choices: ["$24$", "$240$", "$18$", "$-18$"], correctIndex: null },
    { id: "sk1_q5", imageUrl: "/skills/sk01_p003_05.jpg", text: "$4 \\times 3 + (2 \\times 3)^2 =$", choices: ["٤٨", "٣٢٤", "٣٧", "١٨"], correctIndex: null },
    { id: "sk1_q7", imageUrl: "/skills/sk01_p004_02.jpg", text: "$9 - 2(5 - 3)^2 + 6 \\div 2 =$", choices: ["$4$", "$14$", "$30$", "$17$"], correctIndex: null },
    { id: "sk1_q8", imageUrl: "/skills/sk01_p004_03.jpg", text: "إذا كان أ = $2$ ، ب = $3$ أوجد قيمة $\\dfrac{5\\text{أ} + 2\\text{ب}}{2}$", choices: ["$5$", "$6$", "$7$", "$8$"], correctIndex: null },
    { id: "sk1_q9", imageUrl: "/skills/sk01_p004_04.jpg", text: "$3 (\\text{جـ} + 2) - 3 (2 - \\text{جـ}) =$", choices: ["صفر", "٦", "٥ جـ", "٦ جـ"], correctIndex: null },
    { id: "sk1_q10", imageUrl: "/skills/sk01_p004_05.jpg", text: "$5 \\times 8 + 12 \\div 3 - 4 \\times 5 =$", choices: ["$24$", "$20$", "$100$", "$150$"], correctIndex: null },
    { id: "sk1_q11", imageUrl: "/skills/sk01_p004_06.jpg", text: "$8^{2} - 16 - (2 \\times 4) =$", choices: ["٢٠", "٣٠", "٤٠", "٥٠"], correctIndex: null },
    { id: "sk1_q12", imageUrl: "/skills/sk01_p004_07.jpg", text: "$8 \\times 11 - 9 - 5 \\times 11 - 9 =$", choices: ["$47$", "$27$", "$15$", "$72$"], correctIndex: null },
  ] },
  { id: 2, title: "الحساب الذهني", questions: [
    { id: "sk2_q1", imageUrl: "/skills/sk02_p006_01.jpg", text: "$1 + 1 + 1 + \\dots + 1000 = \\dots $", choices: ["$4501500$", "$4498500$", "$9003000$", "$9000000$"], correctIndex: null },
    { id: "sk2_q2", imageUrl: "/skills/sk02_p006_02.jpg", text: "$10001 \\times 30003 = \\dots $", choices: ["$300630003$", "$300600033$", "$300060003$", "$360000033$"], correctIndex: null },
    { id: "sk2_q3", imageUrl: "/skills/sk02_p006_03.jpg", text: "أوجد ناتج ما يلي تقريبًا : $\\dfrac{0.333 \\times 3.09}{4.94 \\times 1.01} = \\dots $", choices: ["$\\dfrac{1}{4}$", "$\\dfrac{3}{4}$", "$\\dfrac{1}{5}$", "$\\dfrac{3}{5}$"], correctIndex: null },
    { id: "sk2_q4", imageUrl: "/skills/sk02_p006_04.jpg", text: "إذا كان مجموع الأعداد من $1$ إلى $10$ يساوي $55$ ما مجموع الأعداد من $1$ إلى $20$ ؟", choices: ["$220$", "$215$", "$210$", "$200$"], correctIndex: null },
    { id: "sk2_q5", imageUrl: "/skills/sk02_p006_05.jpg", text: "$1 + 10 + 100 + 1000 + 10000 - 100 = \\dots $", choices: ["$11011$", "$11001$", "$11101$", "$11110$"], correctIndex: null },
    { id: "sk2_q6", imageUrl: "/skills/sk02_p006_06.jpg", text: "قارن بين:\nالقيمة الأولى: $20 \\times 52$\nالقيمة الثانية: $19 \\times 53$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk2_q7", imageUrl: "/skills/sk02_p007_01.jpg", text: "۹۱ طالب يريدون ركوب حافله وكانت الحافله تستوعب ۲۲ طالب فما اقل عدد من الحافلات يحتاجونه؟", choices: ["٤", "٣", "٥", "٦"], correctIndex: null },
    { id: "sk2_q8", imageUrl: "/skills/sk02_p007_02.jpg", text: "أي القيم الآتية هو الأقل قيمة؟", choices: ["$1 \\times \\dfrac{1}{4}$", "$1 - \\dfrac{1}{4}$", "$1 \\div \\dfrac{1}{4}$", "$1 + \\dfrac{1}{4}$"], correctIndex: null },
    { id: "sk2_q9", imageUrl: "/skills/sk02_p007_03.jpg", text: "٦ أعمدة وكل عمود به عدد من الصناديق أقل من الذي قبله بصندوق واحد فإذا كان العمود الرابع به ٥ صناديق كم مجموع الصناديق؟", choices: ["$29$", "$33$", "$25$", "$24$"], correctIndex: null },
    { id: "sk2_q10", imageUrl: "/skills/sk02_p007_04.jpg", text: "ما خانة الآحاد في حاصل الضرب $326 \\times 48 \\times 342 \\times 524$؟", choices: ["$7$", "$6$", "$8$", "$4$"], correctIndex: null },
    { id: "sk2_q11", imageUrl: "/skills/sk02_p007_05.jpg", text: "ما خانة العشرات في حاصل الضرب $32648 \\times 342524$؟", choices: ["$1$", "$2$", "$3$", "$4$"], correctIndex: null },
    { id: "sk2_q12", imageUrl: "/skills/sk02_p007_06.jpg", text: "أوجد ناتج $444^3 - 443 \\times 444 \\times 445$", choices: ["$444$", "$444^2$", "$-444$", "$-444^2$"], correctIndex: null },
    { id: "sk2_q13", imageUrl: "/skills/sk02_p008_01.jpg", text: "مصنع ينتج $700$ علبة عصير بالأسبوع كم ينتج في السنة؟", choices: ["$350$", "$3500$", "$35000$", "$350000$"], correctIndex: null },
    { id: "sk2_q14", imageUrl: "/skills/sk02_p008_02.jpg", text: "إذا كان مجموع ما مع أحمد ويوسف ٨٥٠ ريال ما مع أحمد يزيد عن ما مع يوسف ١٥٠ ريال فكم مع يوسف؟", choices: ["١٥٠", "٣٥٠", "٤٠٠", "٧٠٠"], correctIndex: null },
    { id: "sk2_q15", imageUrl: "/skills/sk02_p008_03.jpg", text: "ذهب $5$ أشخاص لحفلة ومجموع ما دفعوه $1000$ ريال\nقارن بين:\nالقيمة الأولى: $400$ ريال\nالقيمة الثانية: مقدار ما دفعه شخصان", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
  ] },
  { id: 3, title: "الأعداد العشرية", questions: [
    { id: "sk3_q1", imageUrl: "/skills/sk03_p012_01.jpg", text: "ما قيمة $\\dfrac{0.112 \\times 1.9}{3.94 \\times 0.75}$ تقريبًا", choices: ["$\\dfrac{1}{3}$", "$\\dfrac{3}{4}$", "$\\dfrac{1}{5}$", "$\\dfrac{3}{5}$"], correctIndex: null },
    { id: "sk3_q2", imageUrl: "/skills/sk03_p012_02.jpg", text: "أقرب قيمة إلى $35$", choices: ["$35.001$", "$35.01$", "$35.1$", "$34.8$"], correctIndex: null },
    { id: "sk3_q3", imageUrl: "/skills/sk03_p012_03.jpg", text: "طفل عمره ٤,٢٥ سنة فإن عمره ٤ سنوات و …", choices: ["٤ شهور", "٣ شهور", "٥ شهور", "٦ شهور"], correctIndex: null },
    { id: "sk3_q4", imageUrl: "/skills/sk03_p012_04.jpg", text: "$11,1 + 1,11 + 0,11 + 0,01 = …$", choices: ["$12,44$", "$12,141$", "$12,33$", "$1,111$"], correctIndex: null },
    { id: "sk3_q5", imageUrl: "/skills/sk03_p012_05.jpg", text: "$20.25 + 9.5 = \\dots $", choices: ["$29.30$", "$29.57$", "$29.75$", "$29.7$"], correctIndex: null },
    { id: "sk3_q6", imageUrl: "/skills/sk03_p012_06.jpg", text: "إذا كان $\\dfrac{\\text{س}}{100} + \\dfrac{\\text{ص}}{1000} = 0.047$ ، أوجد قيمة $\\dfrac{\\text{س}}{10} + \\dfrac{\\text{ص}}{100} + \\dfrac{6}{1000}$", choices: ["٠٫٦٤٧", "٠٫٦٧٤", "٠٫٤٧٦", "٠٫٧٤٦"], correctIndex: null },
    { id: "sk3_q7", imageUrl: "/skills/sk03_p012_07.jpg", text: "أوجد مجموع: $0.1 + 0.2 + 0.3 + \\dots + 0.9$", choices: ["$4$", "$4.5$", "$0.45$", "$0.045$"], correctIndex: null },
    { id: "sk3_q8", imageUrl: "/skills/sk03_p013_01.jpg", text: "$2 - 0.001 = \\dots$", choices: ["$1.009$", "$1.099$", "$1.999$", "$1.9999$"], correctIndex: null },
    { id: "sk3_q9", imageUrl: "/skills/sk03_p013_02.jpg", text: "قارن بين:\nالقيمة الأولى: $9 - 0.0044$\nالقيمة الثانية: $9 - 0.00044$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk3_q10", imageUrl: "/skills/sk03_p013_03.jpg", text: "قارن بين:\nالقيمة الأولى: $(0,1)^{22}$\nالقيمة الثانية: $(0,1)^{33}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk3_q11", imageUrl: "/skills/sk03_p013_04.jpg", text: "إذا كان $100 \\times 28 = 7 \\div \\text{س}$ ، أوجد قيمة س", choices: ["$0.25$", "$0.025$", "$0.0025$", "$0.00025$"], correctIndex: null },
  ] },
  { id: 4, title: "الأسس", questions: [
    { id: "sk4_q1", imageUrl: "/skills/sk04_p015_01.jpg", text: "$4^3 + 4^4 = \\dots $", choices: ["$3 \\times 4^4$", "$3 \\times 4^3$", "$5 \\times 4^4$", "$5 \\times 4^3$"], correctIndex: null },
    { id: "sk4_q2", imageUrl: "/skills/sk04_p015_02.jpg", text: "$\\dfrac{10^5 - 10^4}{9} = \\dots $", choices: ["$10^4$", "$10^5$", "$10^{-4}$", "$10^{-5}$"], correctIndex: null },
    { id: "sk4_q3", imageUrl: "/skills/sk04_p015_03.jpg", text: "إذا كان $2^{2013} = 2^{2012} \\times \\text{س}$ ، أوجد قيمة س ؟", choices: ["$2^{\\text{صفر}}$", "$2^1$", "$2^2$", "$2^4$"], correctIndex: null },
    { id: "sk4_q4", imageUrl: "/skills/sk04_p015_04.jpg", text: "إذا كان $2^\\text{ن} + 2^\\text{ن} + 2^\\text{ن} + 2^\\text{ن} = 2^8$ ، ما قيمة ن", choices: ["$2$", "$4$", "$6$", "$8$"], correctIndex: null },
    { id: "sk4_q5", imageUrl: "/skills/sk04_p015_05.jpg", text: "إذا كان $(3\\text{س} + 4)^{\\text{س}-1} = 1$ ، ما قيمة س ؟", choices: ["-١", "صفر", "١", "-١ و ١"], correctIndex: null },
    { id: "sk4_q6", imageUrl: "/skills/sk04_p015_06.jpg", text: "إذا كان $2^{\\text{س}+1} = 6$ ، فما قيمة $16^\\text{س}$", choices: ["$9$", "$16$", "$32$", "$81$"], correctIndex: null },
    { id: "sk4_q7", imageUrl: "/skills/sk04_p015_07.jpg", text: "إذا كان $(2)^\\text{س} = 3$ ، فإن $(2)^{2\\text{س}} = \\dots $", choices: ["$4$", "$6$", "$8$", "$9$"], correctIndex: null },
    { id: "sk4_q8", imageUrl: "/skills/sk04_p015_08.jpg", text: "إذا كان $\\dfrac{2^{2\\text{س} + 1}}{8} = 2^{4 - \\text{س}}$ ، أوجد قيمة س", choices: ["٢", "٣", "٦", "-٦"], correctIndex: null },
    { id: "sk4_q9", imageUrl: "/skills/sk04_p016_01.jpg", text: "إذا كان $0 > \\text{س} > \\text{ص}$\nقارن بين:\nالقيمة الأولى: $(\\text{س})^{2016}$\nالقيمة الثانية: $(\\text{ص})^{2015}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk4_q10", imageUrl: "/skills/sk04_p016_02.jpg", text: "احسب قيمة: $60^{0.75} \\times 12^{0.25} \\times 5^{1.25}$", choices: ["$100$", "$200$", "$300$", "$600$"], correctIndex: null },
    { id: "sk4_q11", imageUrl: "/skills/sk04_p016_03.jpg", text: "قارن بين:\nالقيمة الأولى: $43 \\times 43 \\times 43$\nالقيمة الثانية: $34 \\times 34 \\times 34$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk4_q12", imageUrl: "/skills/sk04_p016_04.jpg", text: "إذا كان س = $7^{77}$ ، ما قيمة $7^{75}$؟", choices: ["$\\dfrac{\\text{س}}{7}$", "$\\dfrac{\\text{س}}{14}$", "$\\dfrac{\\text{س}}{49}$", "$\\dfrac{\\text{س}}{77}$"], correctIndex: null },
  ] },
  { id: 5, title: "أشكال فن والأعداد المحصورة", questions: [
    { id: "sk5_q2", imageUrl: "/skills/sk05_p018_01.jpg", text: "ما عدد الطلاب الذين يدرسون اللغة الإيطالية فقط؟", choices: ["٣", "٨", "١١", "٢٢"], correctIndex: null },
    { id: "sk5_q3", imageUrl: "/skills/sk05_p018_02.jpg", text: "في شكل فن المقابل\nالدائرة (أ) تمثل الموهوبين في الرسم،\nالدائرة (ب) تُمثل الموهوبين في الخط،\nوالدائرة (ج) تُمثل الموهوبين في النحت،\nما عدد الموهوبين في الرسم والخط معا؟", choices: ["$0$", "$7$", "$8$", "$12$"], correctIndex: null },
    { id: "sk5_q4", imageUrl: "/skills/sk05_p018_03.jpg", text: "شكل فن المقابل يوضح عدد المشتركين في مسابقة الرياضيات والكيمياء والفيزياء. أوجد عدد الطلاب المشتركين في الثلاث مواد معا ؟", choices: ["$0$", "$7$", "$8$", "$12$"], correctIndex: null },
    { id: "sk5_q5", imageUrl: "/skills/sk05_p018_04.jpg", text: "قسم المعلم فصل دراسي به ٢٥ شخص إلى قسمين، فإذا كان عدد طلاب القسم الأول ١٩ ، وعدد طلاب القسم الثاني ١١ ، أوجد عدد الطلاب المشترك بين القسمين ؟", choices: ["٥", "٦", "٧", "٨"], correctIndex: null },
    { id: "sk5_q6", imageUrl: "/skills/sk05_p019_01.jpg", text: "أجريت دراسة في أحد الأندية الرياضية على 50 شخص، وجد 30 منهم يمارسون رياضة المشي ، 14 يمارسون رياضة السباحة ، 6 لا يمارسون أيا من الرياضتين ، أوجد عدد الذين يمارسون الرياضتين معا.", choices: ["$0$", "$2$", "$4$", "$6$"], correctIndex: null },
    { id: "sk5_q7", imageUrl: "/skills/sk05_p019_02.jpg", text: "نادي به ٥٠ مشترك، ٣٠ منهم مشتركين في كرة القدم ، ٢٦ مشتركين في السباحة، ٦غير مشتركين في كرة القدم ولا السباحة ، كم عدد المشتركين في كرة القدم والسباحة؟", choices: ["٠", "١٢", "٤", "٦"], correctIndex: null },
    { id: "sk5_q8", imageUrl: "/skills/sk05_p019_03.jpg", text: "١٠ صناديق بها أقلام حبر و رصاص، إذا كان ٤ صناديق بها أقلام حبر، و ٥ صناديق بها أقلام رصاص، صندوقين بها أقلام حبر ورصاص كم عدد الصناديق الفارغة؟", choices: ["١", "٢", "٣", "٤"], correctIndex: null },
    { id: "sk5_q9", imageUrl: "/skills/sk05_p019_04.jpg", text: "كم عدد الأعداد المحصورة بين $3$ ، $99$ ؟", choices: ["$94$", "$95$", "$96$", "$97$"], correctIndex: null },
    { id: "sk5_q10", imageUrl: "/skills/sk05_p019_05.jpg", text: "ترتيب محمد في الفصل من الأمام هو ١٣ وترتيبه من الخلف ١٩ فكم عدد طلاب الفصل؟", choices: ["٣٠", "٣١", "٣٢", "٣٣"], correctIndex: null },
    { id: "sk5_q11", imageUrl: "/skills/sk05_p020_01.jpg", text: "كم عدد الأعداد الصحيحة المحصورة بين $\\sqrt{25}$ و $\\sqrt{144}$ ؟", choices: ["$4$", "$5$", "$6$", "$7$"], correctIndex: null },
    { id: "sk5_q12", imageUrl: "/skills/sk05_p020_02.jpg", text: "١٠ أشخاص ف طابور، خالد ترتيبه الخامس من اليمين، وأحمد ترتيبه الثامن من اليسار، كم شخص يقف بين أحمد وخالد؟", choices: ["١", "٢", "٣", "٤"], correctIndex: null },
    { id: "sk5_q13", imageUrl: "/skills/sk05_p020_03.jpg", text: "إذا كان هناك أعمدة مُرقمة من ١ إلى ٢٠٠ ، وكانت مُقسمة إلى قسمين الأولى تعمل بالطاقة الشمسية والثانية تعمل بالطاقة الكهربائية. فإذا كانت الأعمدة التي تعمل بالطاقة الشمسية يبدأ ترقيمها من ٢٢ إلى ٨٠ ، فما عدد الأعمدة التي تعمل بالطاقة الكهربائية ؟", choices: ["١٤٣", "١٤٢", "١٤١", "١٤٠"], correctIndex: null },
  ] },
  { id: 6, title: "الكسور الاعتيادية", questions: [
    { id: "sk6_q1", imageUrl: "/skills/sk06_p023_01.jpg", text: "قيمة المقدار $\\dfrac{7}{100} + \\dfrac{9}{1000} =$", choices: ["$0.79$", "$0.079$", "$0.0079$", "$0.00079$"], correctIndex: null },
    { id: "sk6_q2", imageUrl: "/skills/sk06_p023_02.jpg", text: "يستخدم دلو سعته $0.004$ م$^3$ لملء حوض ماء سعته $4$ م$^3$، كم دلوًا يستخدم لملء الحوض؟", choices: ["$10$", "$100$", "$1000$", "$10000$"], correctIndex: null },
    { id: "sk6_q3", imageUrl: "/skills/sk06_p023_03.jpg", text: "قارن بين:\nالقيمة الأولى: $\\dfrac{6}{5} - \\dfrac{1}{4}$\nالقيمة الثانية: $\\dfrac{3}{7} - \\dfrac{5}{3}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk6_q4", imageUrl: "/skills/sk06_p023_04.jpg", text: "$1 + \\dfrac{1}{2} \\div \\dfrac{1}{4}$", choices: ["$2$", "$3$", "$4$", "$1$"], correctIndex: null },
    { id: "sk6_q5", imageUrl: "/skills/sk06_p023_05.jpg", text: "$\\dfrac{3}{10} + \\dfrac{7}{100} + \\dfrac{9}{1000} =$", choices: ["$0.379$", "$0.793$", "$0.973$", "$0.0379$"], correctIndex: null },
    { id: "sk6_q6", imageUrl: "/skills/sk06_p023_06.jpg", text: "$\\dfrac{12}{35} + \\dfrac{6}{70} =$", choices: ["$\\dfrac{4}{5}$", "$\\dfrac{5}{4}$", "$\\dfrac{7}{3}$", "$\\dfrac{3}{7}$"], correctIndex: null },
    { id: "sk6_q7", imageUrl: "/skills/sk06_p024_01.jpg", text: "ما قيمة المقدار $1 + \\dfrac{7}{8} + \\dfrac{11}{7} + \\dfrac{3}{7} + \\dfrac{1}{8}$", choices: ["$2$", "$3$", "$4$", "$5$"], correctIndex: null },
    { id: "sk6_q8", imageUrl: "/skills/sk06_p024_02.jpg", text: "إذا كان $\\dfrac{\\text{س}}{9} + \\dfrac{5}{27} = \\dfrac{8}{27}$ من قيمة س ؟", choices: ["$1$", "$3$", "$5$", "$7$"], correctIndex: null },
    { id: "sk6_q9", imageUrl: "/skills/sk06_p024_03.jpg", text: "إذا كان $\\dfrac{2}{\\text{س}} + \\dfrac{5}{\\text{س}} + \\dfrac{3}{\\text{س}} = 20$\nقارن بين:\nالقيمة الأولى: $\\text{س}$\nالقيمة الثانية: $\\dfrac{1}{12} \\div \\dfrac{1}{4}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk6_q10", imageUrl: "/skills/sk06_p024_04.jpg", text: "أبسط صورة للمقدار $\\dfrac{1}{5\\text{س}} + \\dfrac{1}{4\\text{س}}$", choices: ["$\\dfrac{5\\text{س}}{20}$", "$\\dfrac{1}{9\\text{س}}$", "$\\dfrac{1}{\\text{س}^2}$", "$\\dfrac{9}{20\\text{س}}$"], correctIndex: null },
    { id: "sk6_q11", imageUrl: "/skills/sk06_p024_05.jpg", text: "قارن بين:\nالقيمة الأولى: $3$\nالقيمة الثانية: $1 + \\dfrac{1}{5} + \\dfrac{2}{5} + \\dfrac{100}{125}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk6_q12", imageUrl: "/skills/sk06_p025_01.jpg", text: "$\\dfrac{\\sqrt{36}}{6} (\\dfrac{\\text{س}}{2} + \\dfrac{\\text{س}}{3} + \\dfrac{\\text{س}}{6}) =$", choices: ["3س", "6س", "\\dfrac{س}{6}", "س"], correctIndex: null },
    { id: "sk6_q13", imageUrl: "/skills/sk06_p025_02.jpg", text: "مستطيل طوله $40 \\dfrac{1}{3}$ وعرضه $10 \\dfrac{1}{2}$ م يكون محيطه؟", choices: ["$51 \\dfrac{2}{3}$", "$45 \\dfrac{1}{6}$", "$101 \\dfrac{2}{3}$", "$111 \\dfrac{1}{6}$"], correctIndex: null },
    { id: "sk6_q14", imageUrl: "/skills/sk06_p025_03.jpg", text: "إذا كان: $\\dfrac{5\\text{س}}{3} - \\dfrac{3\\text{س}}{2} = 5$ ، أوجد س", choices: ["٢٥", "٣٠", "٣٥", "٢٠"], correctIndex: null },
    { id: "sk6_q15", imageUrl: "/skills/sk06_p025_04.jpg", text: "إذا كان: $\\text{س} + \\dfrac{1}{4} = 4$", choices: ["$3.7$", "$4.5$", "$3.75$", "$5$"], correctIndex: null },
    { id: "sk6_q16", imageUrl: "/skills/sk06_p025_05.jpg", text: "إذا كان $\\dfrac{1}{\\text{س}} + \\dfrac{1}{\\text{ص}} = \\dfrac{1}{4}$ وكانت $\\text{س} + \\text{ص} = 6$ أوجد $\\text{س ص}$؟", choices: ["$6$", "$24$", "$36$", "$12$"], correctIndex: null },
  ] },
  { id: 7, title: "قابلية القسمة على الأعداد", questions: [
    { id: "sk7_q1", imageUrl: "/skills/sk07_p027_01.jpg", text: "مبلغ من المال وزع عن طريق الإرث كالتالي: $\\dfrac{1}{8}$ للزوجة، الذكر مثلي الأنثى، توفي رجل وترك مبلغ من المال $88000$ ريال فما نصيب البنت إذا كان الرجل لديه زوجة، و $9$ أولاد و $4$ بنات.", choices: ["$3000$", "$3500$", "$7000$", "$7500$"], correctIndex: null },
    { id: "sk7_q2", imageUrl: "/skills/sk07_p027_02.jpg", text: "إذا كان: $14 < \\text{س} < \\text{ص} < \\text{ع} < 26$ ، س وَ ص وَ ع أعداد فردية متتالية أحدهم أولي ، أوجد ص + ع ؟", choices: ["٣٦", "٤٠", "٤٤", "٤٨"], correctIndex: null },
    { id: "sk7_q3", imageUrl: "/skills/sk07_p027_03.jpg", text: "أي الأعداد الآتية يمكن كتابته على صورة $6$ ن حيث ن عدد صحيح؟", choices: ["$325$", "$434$", "$222$", "$427$"], correctIndex: null },
    { id: "sk7_q4", imageUrl: "/skills/sk07_p027_04.jpg", text: "إذا وزعت ١٢٠ بيضة على ٩ أطباق بالتساوي، كم بيضة بقيت؟", choices: ["٠", "١", "٢", "٣"], correctIndex: null },
    { id: "sk7_q5", imageUrl: "/skills/sk07_p027_05.jpg", text: "إذا اشترك شخص في باقة جوال ب $42$ ريال شهريا ويحاسب الدقيقة الزائدة أو جزء منها بعد انتهاء الباقة ب $30$ هللة ووصلت فاتورته الشهرية إلى $177$ ريال ، فكم عدد الدقائق الزائدة في هذا الشهر؟", choices: ["$445$", "$446$", "$450$", "$448$"], correctIndex: null },
    { id: "sk7_q6", imageUrl: "/skills/sk07_p027_06.jpg", text: "إذا كان ربع عدد = ٦٠٠٠ ، فما نصف ثلث هذا العدد ؟", choices: ["٣٠٠٠", "٦٠٠٠", "٤٠٠٠", "٨٠٠٠"], correctIndex: null },
    { id: "sk7_q7", imageUrl: "/skills/sk07_p028_01.jpg", text: "عائلة بها ۳ أبناء يعيشون بعيدين عن منزل العائلة، الأول يزور العائلة كل ۳ أيام، والثاني يزور العائلة كل ٥ أيام، والثالث يزور العائلة كل ٦ أيام، فإذا التقوا معا أول العام، فكم مرة يلتقوا معا خلال ٦٠ يوم؟", choices: ["$1$", "$2$", "$3$", "$4$"], correctIndex: null },
    { id: "sk7_q8", imageUrl: "/skills/sk07_p028_02.jpg", text: "شخصين لهم أسهم في شركة وعدد أسهم الثاني يقبل القسمة على $9$ ، $11$ ، $13$، ما نصيب الثاني؟", choices: ["$1323$", "$1387$", "$1457$", "$1521$"], correctIndex: null },
    { id: "sk7_q9", imageUrl: "/skills/sk07_p028_03.jpg", text: "أحمد و $6$ من أصدقاءه تناولوا العشاء وكانت الفاتورة $3710$ وكان ما دفعه كل شخص متساوي.\nقارن بين:\nالقيمة الأولى: ما يدفعه الشخص الواحد\nالقيمة الثانية: $530$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk7_q10", imageUrl: "/skills/sk07_p028_04.jpg", text: "إذا كان لدى شخص ٦٣ ورقة نقدية فإذا كان ثلثها من فئة ٥٠ ريال وسُبعها من فئة ١٠٠ ريال والباقي من فئة ١٠ ريال ، كم المبلغ الذي كان معه؟", choices: ["١١٩٠", "٢١٨٠", "٢٢٨٠", "٢٨٨٠"], correctIndex: null },
    { id: "sk7_q11", imageUrl: "/skills/sk07_p028_05.jpg", text: "مع محمد وخالد ٨٠٠ كتاب وعدد كتب خالد تزيد عن عدد كتب محمد بـ ١٥٠ كتاب ، ما عدد كتب محمد ؟", choices: ["٢٠٠", "٣٠٠", "٣٢٥", "٣٥٠"], correctIndex: null },
    { id: "sk7_q12", imageUrl: "/skills/sk07_p028_06.jpg", text: "شخصين قاما بالقفز على خط الأعداد من الصفر، الأول يقفز كل مرة ٥ والثاني يقفز كل مرة ٣ ، كم عدد الأعداد المشتركة بينهما قبل العدد ١٠٠؟", choices: ["٠", "٢", "٤", "٧"], correctIndex: null },
  ] },
  { id: 8, title: "أنواع الزوايا", questions: [
    { id: "sk8_q4", imageUrl: "/skills/sk08_p033_01.jpg", text: "أوجد قيمة س؟", choices: ["$80^\\circ$", "$20^\\circ$", "$100^\\circ$", "$120^\\circ$"], correctIndex: null },
    { id: "sk8_q5", imageUrl: "/skills/sk08_p033_02.jpg", text: "الشكل المقابل خماسي منتظم أوجد قيمة س", choices: ["$72^\\circ$", "$60^\\circ$", "$80^\\circ$", "$40^\\circ$"], correctIndex: null },
    { id: "sk8_q6", imageUrl: "/skills/sk08_p033_03.jpg", text: "في الشكل المقابل أوجد قيمة س", choices: ["$30^\\circ$", "$60^\\circ$", "$90^\\circ$", "$120^\\circ$"], correctIndex: null },
    { id: "sk8_q7", imageUrl: "/skills/sk08_p033_04.jpg", text: "من الشكل المقابل أوجد قياس زاوية د", choices: ["$150^\\circ$", "$144^\\circ$", "$179^\\circ$", "$208^\\circ$"], correctIndex: null },
    { id: "sk8_q8", imageUrl: "/skills/sk08_p033_05.jpg", text: "في الشكل المجاور ما قيمة س + ص ؟", choices: ["$120^\\circ$", "$140^\\circ$", "$160^\\circ$", "$180^\\circ$"], correctIndex: null },
    { id: "sk8_q9", imageUrl: "/skills/sk08_p034_01.jpg", text: "ما قيمة $\\text{س}$ ؟", choices: ["١٠٠", "٦٠", "٢٤٠", "٣٠"], correctIndex: null },
    { id: "sk8_q10", imageUrl: "/skills/sk08_p034_02.jpg", text: "إذا كان ص = ٥ س، أوجد س ؟", choices: ["$60^\\circ$", "$40^\\circ$", "$80^\\circ$", "$10^\\circ$"], correctIndex: null },
    { id: "sk8_q11", imageUrl: "/skills/sk08_p034_03.jpg", text: "أوجد قياس زاوية س", choices: ["$30^\\circ$", "$40^\\circ$", "$35^\\circ$", "$60^\\circ$"], correctIndex: null },
    { id: "sk8_q12", imageUrl: "/skills/sk08_p034_04.jpg", text: "ما قيمة $\\text{س}$ ؟", choices: ["$60^\\circ$", "$90^\\circ$", "$30^\\circ$", "$120^\\circ$"], correctIndex: null },
    { id: "sk8_q13", imageUrl: "/skills/sk08_p034_05.jpg", text: "أوجد س .", choices: ["$50^\\circ$", "$35^\\circ$", "$25^\\circ$", "$40^\\circ$"], correctIndex: null },
    { id: "sk8_q14", imageUrl: "/skills/sk08_p035_01.jpg", text: "ما قيمة س :", choices: ["$40^\\circ$", "$30^\\circ$", "$45^\\circ$", "$35^\\circ$"], correctIndex: null },
    { id: "sk8_q15", imageUrl: "/skills/sk08_p035_02.jpg", text: "أوجد قياس الزاوية أ م ن؟", choices: ["$20^\\circ$", "$60^\\circ$", "$70^\\circ$", "$90^\\circ$"], correctIndex: null },
  ] },
  { id: 9, title: "الدوريات والأنماط", questions: [
    { id: "sk9_q1", imageUrl: "/skills/sk09_p036_01.jpg", text: "إذا كان ٤ أعواد تكفي لصنع مربع، فكم عود تحتاج لصنع ٧ مربعات متلاصقة؟", choices: ["۲۱", "۲۲", "۲۳", "٢٤"], correctIndex: null },
    { id: "sk9_q2", imageUrl: "/skills/sk09_p036_02.jpg", text: "ما الحد التالي: $0.04$ ، $0.06$ ، $0.08$ ، …", choices: ["$0.1$", "$1$", "$0.9$", "$0.09$"], correctIndex: null },
    { id: "sk9_q3", imageUrl: "/skills/sk09_p036_03.jpg", text: "إذا كان مجموع $1 + 2 + 3 + \\dots + 9 = 45$\nفإن مجموع $10 + 20 + 30 + \\dots + 90 + 100 = \\text{؟}$", choices: ["$450$", "$500$", "$600$", "$550$"], correctIndex: null },
    { id: "sk9_q4", imageUrl: "/skills/sk09_p036_04.jpg", text: "متتابعة حدها الأول $-8$ وللحصول على الحد التالي نضرب $-1$ ثم نضيف $3$\nما هو الحد الحادي والثلاثون؟", choices: ["$11$", "$8$", "$-11$", "$-8$"], correctIndex: null },
    { id: "sk9_q5", imageUrl: "/skills/sk09_p036_05.jpg", text: "إذا كان 8 أشخاص يجلسون على 3 طاولات كما هو مبين بالشكل كم شخص يمكنهم الجلوس على 13 طاولة؟", choices: ["$39$", "$28$", "$25$", "$30$"], correctIndex: null },
    { id: "sk9_q6", imageUrl: "/skills/sk09_p037_01.jpg", text: "هناك 5 بيوت وكل بيت فيه 5 أقفاص وكل قفص فيه 5 عصافير وكل عصفور يأكل 5 حبات قمح، كم حبة قمح أكلت العصافير؟", choices: ["$650$", "$625$", "$225$", "$750$"], correctIndex: null },
    { id: "sk9_q7", imageUrl: "/skills/sk09_p037_02.jpg", text: "ما الرقم في خانة العشرات في ناتج ضرب العددين $(1 \\times 2 \\times 3 \\times 4 \\times 5)$ و $(5 \\times 4 \\times 3 \\times 2 \\times 1)$؟", choices: ["$1$", "$0$", "$4$", "$5$"], correctIndex: null },
    { id: "sk9_q8", imageUrl: "/skills/sk09_p037_03.jpg", text: "احسب قيمة: $1^1 + 1^2 + 1^3 + 1^4 + 1^5 + \\dots + 1^{1433}$", choices: ["صفر", "$1$", "$5$", "$1433$"], correctIndex: null },
    { id: "sk9_q9", imageUrl: "/skills/sk09_p037_04.jpg", text: "$1 + 2 + 3 + 4 + 5 + 6 + 6 + 5 + 4 + 3 + 2 + 1 = \\dots $", choices: ["$8 \\times 7$", "$7 \\times 7$", "$6 \\times 7$", "$2 \\times 7$"], correctIndex: null },
    { id: "sk9_q10", imageUrl: "/skills/sk09_p037_05.jpg", text: "٦ أعمدة وكل عمود به عدد من الصناديق أقل من الذي قبله بصندوق واحد فإذا كان العمود الرابع به ٥ صناديق، كم مجموع الصناديق؟", choices: ["٢٤", "٢٧", "٣٣", "٢٩"], correctIndex: null },
    { id: "sk9_q11", imageUrl: "/skills/sk09_p037_06.jpg", text: "ما الشكل التالي ٣ ، $\\rotatebox{-90}{3}$ ، … ، $\\rotatebox{90}{3}$", choices: ["٣", "$\\rotatebox{-90}{3}$", "$\\rotatebox{180}{3}$", "$\\rotatebox{90}{3}$"], correctIndex: null },
    { id: "sk9_q12", imageUrl: "/skills/sk09_p037_07.jpg", text: "$9$ ، $7$ ، $5$ ، $3$ ، $1$ ، $9$ ، $7$ ، $5$ ، $\\dots$ ما الحد رقم $27$؟", choices: ["$9$", "$7$", "$5$", "$3$"], correctIndex: null },
  ] },
  { id: 10, title: "المثلثات", questions: [
    { id: "sk10_q6", imageUrl: "/skills/sk10_p042_01.jpg", text: "أوجد س =", choices: ["$160^\\circ$", "$80^\\circ$", "$120^\\circ$", "$20^\\circ$"], correctIndex: null },
    { id: "sk10_q7", imageUrl: "/skills/sk10_p042_02.jpg", text: "محيط المثلث =", choices: ["$41$", "$44$", "$43$", "$34$"], correctIndex: null },
    { id: "sk10_q8", imageUrl: "/skills/sk10_p042_03.jpg", text: "مثلث مختلف الأضلاع مجموع أطوال أضلاعه = $21$ سم وطول الضلع الأكبر = $8$ سم ، ما طول أصغر الأضلاع ؟", choices: ["$4$ سم", "$6$ سم", "$7$ سم", "$8$ سم"], correctIndex: null },
    { id: "sk10_q9", imageUrl: "/skills/sk10_p042_04.jpg", text: "ما قيمة $\\text{س}$؟", choices: ["٢٥", "٣٥", "٤٠", "٤٥"], correctIndex: null },
    { id: "sk10_q10", imageUrl: "/skills/sk10_p043_01.jpg", text: "أ ب ج مثلث قائم الزاوية في ب، أوجد قيمة س", choices: ["۲۰", "٢٤", "۷", "۸"], correctIndex: null },
    { id: "sk10_q11", imageUrl: "/skills/sk10_p043_02.jpg", text: "من الرسم المقابل أوجد طول أ ب", choices: ["$13$", "$12$", "$20$", "$8$"], correctIndex: null },
    { id: "sk10_q12", imageUrl: "/skills/sk10_p043_03.jpg", text: "أحسب محيط الشكل المرسوم", choices: ["$24$", "$10$", "$16$", "$34$"], correctIndex: null },
    { id: "sk10_q13", imageUrl: "/skills/sk10_p043_04.jpg", text: "أوجد قيمة س", choices: ["$6$", "$8$", "$10$", "$12$"], correctIndex: null },
    { id: "sk10_q14", imageUrl: "/skills/sk10_p044_01.jpg", text: "أوجد طول أ د في الشكل المرسوم", choices: ["$3$", "$3\\sqrt{5}$", "$\\sqrt{5}$", "$7$"], correctIndex: null },
    { id: "sk10_q15", imageUrl: "/skills/sk10_p044_02.jpg", text: "أوجد قيمة س على الرسم", choices: ["$4$", "$5$", "$9$", "$20$"], correctIndex: null },
    { id: "sk10_q16", imageUrl: "/skills/sk10_p044_03.jpg", text: "أوجد محيط المثلث", choices: ["$43$", "$44$", "$31$", "$43$"], correctIndex: null },
    { id: "sk10_q17", imageUrl: "/skills/sk10_p044_04.jpg", text: "مثلث يزيد ارتفاعه عن قاعدته بمقدار $1$ سم و مساحته $21$ سم$^2$ فما طول ارتفاعه؟", choices: ["$4$ سم", "$5$ سم", "$6$ سم", "$7$ سم"], correctIndex: null },
  ] },
  { id: 11, title: "عدد المستطيلات والمربعات والمثلثات", questions: [
    { id: "sk11_q3", imageUrl: "/skills/sk11_p047_01.jpg", text: "كم عدد المستطيلات في الشكل؟", choices: ["$5$", "$10$", "$15$", "$30$"], correctIndex: null },
    { id: "sk11_q4", imageUrl: "/skills/sk11_p047_02.jpg", text: "كم عدد المستطيلات في الشكل؟", choices: ["$25$", "$35$", "$45$", "$11$"], correctIndex: null },
    { id: "sk11_q5", imageUrl: "/skills/sk11_p047_03.jpg", text: "كم عدد المربعات في الشكل؟", choices: ["$5$", "$10$", "$15$", "$30$"], correctIndex: null },
    { id: "sk11_q6", imageUrl: "/skills/sk11_p047_04.jpg", text: "كم عدد المربعات في الشكل؟", choices: ["$5$", "$10$", "$14$", "$30$"], correctIndex: null },
    { id: "sk11_q7", imageUrl: "/skills/sk11_p047_05.jpg", text: "كم عدد المثلثات في الشكل ؟", choices: ["$13$", "$14$", "$15$", "$16$"], correctIndex: null },
    { id: "sk11_q8", imageUrl: "/skills/sk11_p047_06.jpg", text: "كم عدد المستطيلات في الشكل ؟", choices: ["$9$", "$10$", "$8$", "$5$"], correctIndex: null },
    { id: "sk11_q9", imageUrl: "/skills/sk11_p048_01.jpg", text: "كم عدد المربعات في الشكل المقابل؟", choices: ["١٣", "١٥", "١٢", "١١"], correctIndex: null },
    { id: "sk11_q10", imageUrl: "/skills/sk11_p048_02.jpg", text: "قارن بين:\nالقيمة الأولى: مساحة المظلل\nالقيمة الثانية: $8\\text{ سم}^2$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk11_q11", imageUrl: "/skills/sk11_p048_03.jpg", text: "قارن بين:\nالقيمة الأولى: $6$\nالقيمة الثانية: عدد القطع المستقيمة في الشكل", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk11_q12", imageUrl: "/skills/sk11_p048_04.jpg", text: "كم عود ثقاب نحتاج لعمل $12$ مثلث متلاصق؟", choices: ["$22$", "$23$", "$24$", "$25$"], correctIndex: null },
    { id: "sk11_q13", imageUrl: "/skills/sk11_p048_05.jpg", text: "كم عدد الأعواد اللازمة لعمل $12$ مربع متلاصق؟", choices: ["$23$", "$35$", "$36$", "$37$"], correctIndex: null },
    { id: "sk11_q14", imageUrl: "/skills/sk11_p048_06.jpg", text: "تقابل عدد من الأصدقاء في مؤتمر علمي وصافح كلا منهما الأخر وكان عدد المصافحات $21$ مصافحة. فكم عدد الأصدقاء؟", choices: ["$5$", "$6$", "$7$", "$8$"], correctIndex: null },
  ] },
  { id: 12, title: "المتوسط والوسيط والمنوال", questions: [
    { id: "sk12_q1", imageUrl: "/skills/sk12_p049_01.jpg", text: "إذا كان $13^\\text{س} \\times 13^\\text{ص} = 13^{14}$ ، ما المتوسط الحسابي للعددين س ، ص ؟", choices: ["$3$", "$7$", "$13$", "$14$"], correctIndex: null },
    { id: "sk12_q2", imageUrl: "/skills/sk12_p049_02.jpg", text: "المتوسط الحسابي لمنوال ووسيط الأعداد $8 , 6 , 5 , 5 , 5 , 4 , 3$", choices: ["$3$", "$4$", "$5$", "$6$"], correctIndex: null },
    { id: "sk12_q3", imageUrl: "/skills/sk12_p049_03.jpg", text: "المتوسط الحسابي لأكبر عدد زوجي مكون من رقمين مع أصغر عدد أولي", choices: ["٣٠", "٤٠", "٥٠", "٦٠"], correctIndex: null },
    { id: "sk12_q4", imageUrl: "/skills/sk12_p049_04.jpg", text: "ثلاثة أعداد ٥ ، ٩ ، س متوسطهم = ١١ ، ما قيمة س؟", choices: ["٩", "١٩", "٢٩", "٣٣"], correctIndex: null },
    { id: "sk12_q5", imageUrl: "/skills/sk12_p050_01.jpg", text: "إذا كان متوسط خمسة أعداد = $9$ ومتوسط $4$ أعداد منهم = $10$ ، ما العدد الخامس ؟", choices: ["$3$", "$4$", "$5$", "$6$"], correctIndex: null },
    { id: "sk12_q6", imageUrl: "/skills/sk12_p050_02.jpg", text: "اختبار درجته العظمى $100$ درجة ، فإذا كان متوسط درجات $4$ طلاب = $90$ فما أقل درجة ممكنة يحصل عليها طالب منهم ؟", choices: ["$60$", "$40$", "$30$", "$20$"], correctIndex: null },
    { id: "sk12_q7", imageUrl: "/skills/sk12_p050_03.jpg", text: "أربعة أعداد متوسطهم = $24$ ومتوسط أول عددين = $10$ ، ما مجموع العددين الآخرين؟", choices: ["$36$", "$37$", "$38$", "$76$"], correctIndex: null },
    { id: "sk12_q8", imageUrl: "/skills/sk12_p050_04.jpg", text: "إذا كان المتوسط الحسابي للعددين $6$ ، ك يساوي المتوسط الحسابي للأعداد $2$ ، $9$ ، ك\nقارن بين:\nالقيمة الأولى: ك\nالقيمة الثانية: $4$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk12_q9", imageUrl: "/skills/sk12_p050_05.jpg", text: "أوجد متوسط القيم بالشكل", choices: ["$20$", "$25$", "$30$", "$35$"], correctIndex: null },
    { id: "sk12_q10", imageUrl: "/skills/sk12_p051_01.jpg", text: "ما متوسط عدد المخالفات بعد تركيب ساهر في الرياض؟", choices: ["$4$", "$4.5$", "$5$", "$5.5$"], correctIndex: null },
    { id: "sk12_q11", imageUrl: "/skills/sk12_p051_02.jpg", text: "ما هو الوسيط لعدد الأطفال ؟", choices: ["$6$", "$5$", "$3$", "$8$"], correctIndex: null },
    { id: "sk12_q12", imageUrl: "/skills/sk12_p051_03.jpg", text: "أوجد متوسط ربح أحمد ومحمد وصالح عام ١٤١٩", choices: ["٢٠٠٠", "٣٠٠٠", "٤٠٠٠", "٥٠٠٠"], correctIndex: null },
  ] },
  { id: 13, title: "المعادلات", questions: [
    { id: "sk13_q1", imageUrl: "/skills/sk13_p052_01.jpg", text: "إذا كان $\\dfrac{5}{\\text{س}} - \\dfrac{3}{7} = \\dfrac{2}{\\text{س}}$ فإن س =", choices: ["$8$", "$7$", "$9$", "$6$"], correctIndex: null },
    { id: "sk13_q2", imageUrl: "/skills/sk13_p052_02.jpg", text: "إذا كان $\\text{ن} = 2$ ، قارن بين:\nالقيمة الأولى: $\\dfrac{\\text{ن} (\\text{ن} - 1)^2}{\\text{ن} \\times 4}$\nالقيمة الثانية: $1 \\div \\text{ن}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk13_q3", imageUrl: "/skills/sk13_p052_03.jpg", text: "إذا كان $5$ س = $4$ ل، قارن بين:\nالقيمة الأولى: س\nالقيمة الثانية: ل", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk13_q4", imageUrl: "/skills/sk13_p052_04.jpg", text: "إذا كان $\\text{س} + \\text{ص} = 2$ ، قارن بين:\nالقيمة الأولى: $\\dfrac{\\text{س} + \\text{ص} + 1}{\\text{س} + \\text{ص}}$\nالقيمة الثانية: $2$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk13_q5", imageUrl: "/skills/sk13_p052_05.jpg", text: "إذا كان $\\dfrac{1}{(\\text{س} - 1)^4} = \\dfrac{1}{10000}$ فأوجد س", choices: ["$8$", "$10$", "$-9$", "$12$"], correctIndex: null },
    { id: "sk13_q6", imageUrl: "/skills/sk13_p053_01.jpg", text: "إذا كان ل = ق + ٥ ، ل عدد اولي اي مما يلي هو قيمه ق", choices: ["٥", "٩", "٤", "٨"], correctIndex: null },
    { id: "sk13_q7", imageUrl: "/skills/sk13_p053_02.jpg", text: "إذا كان $\\text{س} + \\text{ص} = 7$ حيث $\\text{س}$ ، $\\text{ص}$ أعداد صحيحة موجبة فأي الآتي صحيح؟", choices: ["$\\text{س} = 7$", "$\\text{س} = 6$", "$\\text{ص} = 7$", "$\\text{ص} = 9$"], correctIndex: null },
    { id: "sk13_q8", imageUrl: "/skills/sk13_p053_03.jpg", text: "مستطيل مساحته ($2\\text{س}^2 + 11\\text{س} + 15$) وطوله ($\\text{س} + 3$)\nما عرض المستطيل؟", choices: ["$2\\text{س} - 5$", "$2\\text{س} + 5$", "$\\text{س} + 5$", "$2\\text{س} + 3$"], correctIndex: null },
    { id: "sk13_q9", imageUrl: "/skills/sk13_p053_04.jpg", text: "ما العدد الذي يساوي ثلاثة أمثال جذره التربيعي ؟", choices: ["$4$", "$9$", "$16$", "$81$"], correctIndex: null },
    { id: "sk13_q10", imageUrl: "/skills/sk13_p053_05.jpg", text: "إذا كان س + ص = ١٠ ، س - ص = صفر ، أوجد قيمة س", choices: ["٢", "٥", "٧", "١٠"], correctIndex: null },
    { id: "sk13_q11", imageUrl: "/skills/sk13_p053_06.jpg", text: "اشترى صالح شماغ بمبلغ ٨٠ ريال واشترى مشعل شماغ سعره يزيد ٤٠ ريال عن سعر شماغ صالح، كم سعر شماغ مشعل؟", choices: ["١٢٠", "٨٠", "٦٠", "٤٠"], correctIndex: null },
    { id: "sk13_q12", imageUrl: "/skills/sk13_p053_07.jpg", text: "عدد قوائم البقر = $48$ ، إذا كان عدد الحمام = ضعف عدد البقر ، ما عدد الحمام ؟", choices: ["$12$", "$24$", "$36$", "$32$"], correctIndex: null },
  ] },
  { id: 14, title: "التوازي", questions: [
    { id: "sk14_q1", imageUrl: "/skills/sk14_p055_01.jpg", text: "قارن بين:\nالقيمة الأولى: $\\text{س}$\nالقيمة الثانية: $2\\text{ص}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk14_q2", imageUrl: "/skills/sk14_p055_02.jpg", text: "أوجد قيمة س", choices: ["$60^\\circ$", "$80^\\circ$", "$90^\\circ$", "$100^\\circ$"], correctIndex: null },
    { id: "sk14_q3", imageUrl: "/skills/sk14_p055_03.jpg", text: "أوجد قيمة $10$ س", choices: ["$100$", "$130$", "$160$", "$230$"], correctIndex: null },
    { id: "sk14_q4", imageUrl: "/skills/sk14_p055_04.jpg", text: "في الشكل المقابل ما قيمة $\\text{س} + \\text{ص}$", choices: ["١٤٠", "١٦٠", "١٠٠", "١٢٠"], correctIndex: null },
    { id: "sk14_q5", imageUrl: "/skills/sk14_p055_05.jpg", text: "أوجد قيمة الزاوية هـ", choices: ["$^\\circ 30$", "$^\\circ 40$", "$^\\circ 70$", "$^\\circ 110$"], correctIndex: null },
    { id: "sk14_q6", imageUrl: "/skills/sk14_p056_01.jpg", text: "اوجد قياس زاويه س", choices: ["$50^\\circ$", "$80^\\circ$", "$130^\\circ$", "$150^\\circ$"], correctIndex: null },
    { id: "sk14_q7", imageUrl: "/skills/sk14_p056_02.jpg", text: "قارن بين:\nالقيمة الأولى: $130^\\circ$\nالقيمة الثانية: $\\text{س}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk14_q8", imageUrl: "/skills/sk14_p056_03.jpg", text: "أوجد قيمة س", choices: ["$25^\\circ$", "$65^\\circ$", "$115^\\circ$", "$120^\\circ$"], correctIndex: null },
    { id: "sk14_q9", imageUrl: "/skills/sk14_p056_04.jpg", text: "أوجد قيمة س", choices: ["$26^\\circ$", "$154^\\circ$", "$64^\\circ$", "$74^\\circ$"], correctIndex: null },
    { id: "sk14_q10", imageUrl: "/skills/sk14_p056_05.jpg", text: "أوجد قيمة س", choices: ["$55^\\circ$", "$75^\\circ$", "$125^\\circ$", "$145^\\circ$"], correctIndex: null },
    { id: "sk14_q11", imageUrl: "/skills/sk14_p057_01.jpg", text: "ما قيمة ص؟", choices: ["$40^\\circ$", "$90^\\circ$", "$60^\\circ$", "$30^\\circ$"], correctIndex: null },
    { id: "sk14_q12", imageUrl: "/skills/sk14_p057_02.jpg", text: "قارن بين:\nالقيمة الأولى: $3\\text{س} + 2\\text{ص}$\nالقيمة الثانية: $180^\\circ$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
  ] },
  { id: 15, title: "السرعة والمسافة والزمن", questions: [
    { id: "sk15_q1", imageUrl: "/skills/sk15_p060_01.jpg", text: "سيارة تسير بسرعة ١٢٠ كم / س أوجد المسافة المقطوعة خلال ٣٠ دقيقة", choices: ["٦٠ كم", "٣٠ كم", "٨٠ كم", "١٢٠٠ كم"], correctIndex: null },
    { id: "sk15_q2", imageUrl: "/skills/sk15_p060_02.jpg", text: "شخص يقطع $8$ كم / س ، كم ساعة يحتاج ليقطع $48$ كم؟", choices: ["$8$", "$6$", "$5$", "$7$"], correctIndex: null },
    { id: "sk15_q3", imageUrl: "/skills/sk15_p060_03.jpg", text: "سائق يسير بسرعة ١٢٠ كم / س ليصل بعد ٢ ساعة، إذا وصل بعد ٣ ساعات كم تكون سرعته؟", choices: ["١٠٠ كم / س", "٦٠ كم / س", "٨٠ كم / س", "٧٠ كم / س"], correctIndex: null },
    { id: "sk15_q4", imageUrl: "/skills/sk15_p060_04.jpg", text: "دراجة هوائية تسير بسرعة $20$ كم / س ودراجة نارية تسير بسرعة $95$ كم / س فإذا ساروا في نفس الاتجاه، فكم تكون المسافة بينهما بعد مرور ساعتين؟", choices: ["$75$ كم", "$150$ كم", "$200$ كم", "$225$ كم"], correctIndex: null },
    { id: "sk15_q5", imageUrl: "/skills/sk15_p060_05.jpg", text: "ذهب شخص من الرياض إلى الدمام بسرعة مقدارها $110$ كم / ساعة، وعاد إلى الرياض بسرعة مقدارها $90$ كم / ساعة، احسب سرعته المتوسطة؟", choices: ["$99$ كم / س", "$100$ كم / س", "$90$ كم / س", "$110$ كم / س"], correctIndex: null },
    { id: "sk15_q6", imageUrl: "/skills/sk15_p060_06.jpg", text: "تقطع سيارة $200$ كم ذهابًا في $3$ ساعات ثم تعود لتقطع نفس المسافة في $2$ ساعة، فما السرعة المتوسطة للسيارة؟", choices: ["80 كم / س", "100 كم / س", "120 كم / س", "60 كم / س"], correctIndex: null },
    { id: "sk15_q7", imageUrl: "/skills/sk15_p061_01.jpg", text: "بعد كم دقيقة يلتقيان؟", choices: ["$15$ د", "$20$ د", "$25$ د", "$80$ د"], correctIndex: null },
    { id: "sk15_q8", imageUrl: "/skills/sk15_p061_02.jpg", text: "سيارة تمشي بسرعة ٦٠ كم / س وبعد نصف ساعة تحركت سيارة أخرى بسرعة ٨٠ كم / س، متى تلتقي السيارتان؟", choices: ["١ ساعة", "١,٥ ساعة", "ساعتان", "٤ ساعات"], correctIndex: null },
    { id: "sk15_q9", imageUrl: "/skills/sk15_p061_03.jpg", text: "سيارتان تتجهان من المدينة أ إلى المدينة ب الأولى بسرعة $100$ كم / س والثانية بسرعة $120$ كم / س، والمسافة بين المدينتين $480$ كم فما الفرق بين زمن الوصول بينهما بالدقائق؟", choices: ["$40$", "$48$", "$50$", "$60$"], correctIndex: null },
    { id: "sk15_q10", imageUrl: "/skills/sk15_p061_04.jpg", text: "قطار يقطع مسافة ۲۲۰ كم في ۳ ساعات، فكم ساعة يلزم ليقطع ۱۱۰۰ كم", choices: ["۱۸", "١٦", "١٥", "١٤"], correctIndex: null },
    { id: "sk15_q11", imageUrl: "/skills/sk15_p061_05.jpg", text: "انطلقت سيارة من النقطة أ إلى النقطة ب بسرعة ١٢٠ كم / س، في نفس اللحظة انطلقت سيارة من النقطة ب إلى النقطة أ بسرعة ٩٠ كم / س،\nبعد كم دقيقة يلتقيان إذا كانت المسافة بين أ و ب ٤٢٠ كم ؟", choices: ["٦٠ د", "٩٠ د", "١٢٠ د", "١٨٠ د"], correctIndex: null },
    { id: "sk15_q12", imageUrl: "/skills/sk15_p061_06.jpg", text: "سيارة تمشي بسرعة ٤٤ كم / س ونصف قطر العجلة = ٠,٧ م، احسب عدد دورات العجلة في زمن قدره ساعة ؟", choices: ["١٠٠", "١٠٠٠", "١٠٠٠٠", "١٠٠٠٠٠"], correctIndex: null },
  ] },
  { id: 16, title: "المستطيل", questions: [
    { id: "sk16_q1", imageUrl: "/skills/sk16_p065_01.jpg", text: "أوجد مساحة المستطيلات المظللة", choices: ["$3$", "$10$", "$15$", "$18$"], correctIndex: null },
    { id: "sk16_q2", imageUrl: "/skills/sk16_p065_02.jpg", text: "إذا كان محيط المربع المجاور = $32$ ، فاحسب مساحة المستطيل الصغير.", choices: ["$20$", "$18$", "$12$", "$16$"], correctIndex: null },
    { id: "sk16_q3", imageUrl: "/skills/sk16_p066_01.jpg", text: "إذا كان محيط المستطيل = $14$ سم، فما قيمة $\\text{س}$؟", choices: ["$5$", "$6$", "$7$", "$8$"], correctIndex: null },
    { id: "sk16_q4", imageUrl: "/skills/sk16_p066_02.jpg", text: "إذا كان محيط المربع = محيط المستطيل\nقارن بين:\nالقيمة الأولى: مساحة المربع\nالقيمة الثانية: مساحة المستطيل", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk16_q5", imageUrl: "/skills/sk16_p066_03.jpg", text: "ورقة مستطيلة طويت لتحصل على مستطيلين أبعاد كل واحد ٤ سم ، ٦ سم فما مساحة الورقة؟", choices: ["٤٨", "٢٤", "١٦", "٢٠"], correctIndex: null },
    { id: "sk16_q6", imageUrl: "/skills/sk16_p066_04.jpg", text: "مستطيل مساحته $150$ سم$^2$ ومحيطه $50$ سم فكم طوله ؟", choices: ["$10$ سم", "$15$ سم", "$20$ سم", "$22$ سم"], correctIndex: null },
    { id: "sk16_q7", imageUrl: "/skills/sk16_p066_05.jpg", text: "سلك طوله $30$ سم تم طويه على شكل مستطيل مساحته $44\\text{ سم}^2$ أوجد الفرق بين الطول والعرض.", choices: ["$7$", "$15$", "$4$", "$11$"], correctIndex: null },
    { id: "sk16_q8", imageUrl: "/skills/sk16_p066_06.jpg", text: "مثلث أضلاعه $6$ ، $8$ ، $10$ مساحته تساوي مساحة مستطيل أحد أضلاعه $8$ ،\nما محيط المستطيل ؟", choices: ["$11$", "$22$", "$30$", "$32$"], correctIndex: null },
    { id: "sk16_q9", imageUrl: "/skills/sk16_p067_01.jpg", text: "إذا علمت أن الشكل مستطيل ، ا هـ = ب هـ = 5 ، طول د ج = 8 فأوجد مساحة المستطيل.", choices: ["٤٥", "٢٤", "١٢", "٢٠"], correctIndex: null },
    { id: "sk16_q10", imageUrl: "/skills/sk16_p067_02.jpg", text: "الشكل أدناه مستطيل ومربع، ما مساحة المربع ؟", choices: ["$3$", "$6$", "$9$", "$12$"], correctIndex: null },
    { id: "sk16_q11", imageUrl: "/skills/sk16_p067_03.jpg", text: "ما مساحة الشكل ؟", choices: ["$140$", "$132$", "$112$", "$108$"], correctIndex: null },
    { id: "sk16_q12", imageUrl: "/skills/sk16_p067_04.jpg", text: "مستطيل طوله يزيد عن عرضه بمقدار $2$ سم و طول قطره $10$ سم ، قارن بين:\nالقيمة الأولى: مساحة المستطيل\nالقيمة الثانية: $24\\text{ سم}^2$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
  ] },
  { id: 17, title: "المتطابقات", questions: [
    { id: "sk17_q1", imageUrl: "/skills/sk17_p069_01.jpg", text: "إذا كان س ص = $50$ ، س $\\div$ ص = $2$ ، ما قيمة س ؟", choices: ["$5$", "$10$", "$20$", "$25$"], correctIndex: null },
    { id: "sk17_q2", imageUrl: "/skills/sk17_p069_02.jpg", text: "إذا كان $\\dfrac{\\text{س}^2 - 1}{\\text{س} - 1} = 8$ ، أوجد قيمة س + 1", choices: ["$2$", "$4$", "$6$", "$8$"], correctIndex: null },
    { id: "sk17_q3", imageUrl: "/skills/sk17_p069_03.jpg", text: "إذا كان قيمة $(\\text{س} - \\text{ص})^2 = \\dfrac{1}{5}$ فما قيمة $(\\text{ص} - \\text{س})^2$", choices: ["$-5$", "-\\dfrac{1}{5}", "\\dfrac{1}{5}", "$5$"], correctIndex: null },
    { id: "sk17_q4", imageUrl: "/skills/sk17_p069_04.jpg", text: "إذا كان $(\\text{أ} + \\text{ب})^2 = 64$ ، $\\text{أ}^2 + \\text{ب}^2 = 24$ أوجد قيمة $\\dfrac{\\text{أ ب}}{2}$", choices: ["$7.5$", "$10$", "$15$", "$20$"], correctIndex: null },
    { id: "sk17_q5", imageUrl: "/skills/sk17_p069_05.jpg", text: "$\\dfrac{\\text{س}(\\text{س}^2 - \\text{ص}^2)}{\\text{س} + \\text{ص}} = …$", choices: ["$\\text{س} - \\text{ص}$", "$\\text{س} - \\text{س ص}$", "$\\text{س}^2 + \\text{س ص}$", "$\\text{س}^2 - \\text{س ص}$"], correctIndex: null },
    { id: "sk17_q6", imageUrl: "/skills/sk17_p069_06.jpg", text: "إذا كان $\\text{أ} - \\text{ب} = 3$ ، $\\text{ب} - \\text{ج} = 5$ ، $\\text{ج} + \\text{د} = 1$ ، ما قيمة $\\text{أ} + \\text{د}$", choices: ["$2$", "$8$", "$9$", "$10$"], correctIndex: null },
    { id: "sk17_q7", imageUrl: "/skills/sk17_p070_01.jpg", text: "إذا كان $\\text{س} - \\text{ص} = 5$ ، $\\text{س ص} = 10$ ، اوجد $\\text{س}^2 + \\text{ص}^2$", choices: ["$5$", "$25$", "$45$", "$55$"], correctIndex: null },
    { id: "sk17_q8", imageUrl: "/skills/sk17_p070_02.jpg", text: "$(\\text{س} + \\text{ص})^2 - 2 \\text{س ص} + (\\text{س} - \\text{ص})^2 + 2 \\text{س ص} = …$", choices: ["$\\text{س}^2 - \\text{ص}^2$", "$2(\\text{س}^2 + \\text{ص}^2)$", "$2(\\text{س} - \\text{ص})^2$", "$2(\\text{س} + \\text{ص})^2$"], correctIndex: null },
    { id: "sk17_q9", imageUrl: "/skills/sk17_p070_03.jpg", text: "$\\text{س} + \\text{ص} = 6$ فإن أكبر قيمة لـ $\\text{س} \\times \\text{ص}$؟", choices: ["$5$", "$8$", "$9$", "$12$"], correctIndex: null },
    { id: "sk17_q10", imageUrl: "/skills/sk17_p070_04.jpg", text: "إذا كان $\\dfrac{\\text{أ + ب + ج + د}}{4} = 8$ ، $\\text{أ + ب} = 10$ أوجد قيمة $\\dfrac{\\text{ج + د}}{2}$", choices: ["$10$", "$11$", "$12$", "$13$"], correctIndex: null },
    { id: "sk17_q11", imageUrl: "/skills/sk17_p070_05.jpg", text: "إذا كان $(2\\text{ص} - \\text{س}) \\times (2\\text{س} - \\text{ص}) = \\text{م}$ أوجد قيمة $(\\text{س} - 2\\text{ص}) \\times (3\\text{ص} - 6\\text{س})$", choices: ["$-2\\text{م}$", "$-3\\text{م}$", "$2\\text{م}$", "$3\\text{م}$"], correctIndex: null },
    { id: "sk17_q12", imageUrl: "/skills/sk17_p070_06.jpg", text: "إذا كان أ ، ب ، جـ أعداد طبيعية $\\text{أ}^3 - 8 = \\text{صفر}$ ، $\\text{ب}^2 - 4 = \\text{صفر}$ ، $\\text{جـ} - 8 = \\text{صفر}$ ،\nأوجد أ + ب + جـ", choices: ["$8$", "$10$", "$12$", "$16$"], correctIndex: null },
  ] },
  { id: 18, title: "المربع", questions: [
    { id: "sk18_q1", imageUrl: "/skills/sk18_p072_01.jpg", text: "إذا كان (ن) هو طول ضلع مربع، أي الآتي يمثل محيط هذا المربع؟", choices: ["$2\\text{ن}$", "$\\text{ن}^2$", "$4\\text{ن}$", "$8\\text{ن}$"], correctIndex: null },
    { id: "sk18_q2", imageUrl: "/skills/sk18_p072_02.jpg", text: "أوجد مساحة المربع", choices: ["$16$", "$32$", "$48$", "$64$"], correctIndex: null },
    { id: "sk18_q3", imageUrl: "/skills/sk18_p072_03.jpg", text: "إذا كان م مركز المربع أوجد قيمة ص", choices: ["$30^\\circ$", "$45^\\circ$", "$60^\\circ$", "$75^\\circ$"], correctIndex: null },
    { id: "sk18_q4", imageUrl: "/skills/sk18_p072_04.jpg", text: "إذا كان الشكل مربع ، أوجد قيمة س", choices: ["$9$", "$4$", "$3$", "$1$"], correctIndex: null },
    { id: "sk18_q5", imageUrl: "/skills/sk18_p072_05.jpg", text: "مساحة مربع ضعف مساحة مستطيل إذا كان طول المستطيل هو $9$ و عرضه هو $2$ احسب طول ضلع المربع ؟", choices: ["$5$ سم", "$6$ سم", "$7$ سم", "$8$ سم"], correctIndex: null },
    { id: "sk18_q6", imageUrl: "/skills/sk18_p073_01.jpg", text: "قارن بين:\nالقيمة الأولى: مساحة المربع أ ب جـ د\nالقيمة الثانية: $15 \\text{ سم}^2$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk18_q8", imageUrl: "/skills/sk18_p073_03.jpg", text: "قارن بين:\nالقيمة الأولى: مساحة الجزء المظلل\nالقيمة الثانية: $\\dfrac{1}{4}$ مساحة المربع", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk18_q9", imageUrl: "/skills/sk18_p073_04.jpg", text: "حسب الأطوال على الرسم\nاحسب مساحة المربع الصغير", choices: ["$20$", "$10$", "$16$", "$8$"], correctIndex: null },
    { id: "sk18_q10", imageUrl: "/skills/sk18_p074_01.jpg", text: "إذا كان محيط المربع $48$ سم مقسم إلى $4$ مستطيلات متطابقة\nأوجد مساحة المستطيل الصغير", choices: ["$36\\text{ سم}^2$", "$38\\text{ سم}^2$", "$40\\text{ سم}^2$", "$48\\text{ سم}^2$"], correctIndex: null },
    { id: "sk18_q12", imageUrl: "/skills/sk18_p074_03.jpg", text: "إذا كانت مساحة المربع الكبير = $24$ فأوجد مساحة المربع الصغير", choices: ["$6$", "$8$", "$4$", "$12$"], correctIndex: null },
  ] },
  { id: 19, title: "الأعمار والأوراق النقدية", questions: [
    { id: "sk19_q1", imageUrl: "/skills/sk19_p075_01.jpg", text: "إذا كان ما مع محمد $2200$ ريال من فئة $500$ و $200$ ريال وكان عدد الأوراق معه $8$ أوراق فكم ورقه معه من فئة $200$ ريال؟", choices: ["$6$", "$7$", "$8$", "$9$"], correctIndex: null },
    { id: "sk19_q2", imageUrl: "/skills/sk19_p075_02.jpg", text: "مع خالد ١٤٠ ريال من فئة ٥ ريال وفئة ١٠ ريال ومجموع الأوراق التي معه ١٨ ورقة فكم عدد الأوراق من فئة الـ ٥ ريال؟", choices: ["٦", "٨", "٧", "٩"], correctIndex: null },
    { id: "sk19_q3", imageUrl: "/skills/sk19_p075_03.jpg", text: "إذا كان عمر أمل ثُلث عمر أختها وبعد 6 سنوات تصبح أمل نصف عمر أختها فكم عمر أمل الآن؟", choices: ["$5$", "$6$", "$18$", "$20$"], correctIndex: null },
    { id: "sk19_q4", imageUrl: "/skills/sk19_p076_01.jpg", text: "شخص معه مبلغ مقداره ٤٨٠ ريال من فئات ١٠٠ و ٥٠ و ١٠ وكان عدد الأوراق متساوية من كل فئة فإن عدد الأوراق لكل فئة", choices: ["٣", "٤", "٥", "٦"], correctIndex: null },
    { id: "sk19_q5", imageUrl: "/skills/sk19_p076_02.jpg", text: "إذا كان شخص يملك $12$ ريال من فئة ريال ونصف ريال ، وكان مجموع القطع $15$ قطعة فكم عدد القطع من فئة نصف ريال؟", choices: ["$3$", "$6$", "$8$", "$9$"], correctIndex: null },
    { id: "sk19_q6", imageUrl: "/skills/sk19_p076_03.jpg", text: "رجل معه ۱۲۰ ورقة نقدية من فئة ۱۰ و ٥ إذا كان عدد أوراق فئة ۱۰ ريال = ٥ أمثال فئة ٥ ريال، فكم المبلغ الكلي؟", choices: ["٦٠٠", "٧٠٠", "٧٥٠", "۱۱۰۰"], correctIndex: null },
    { id: "sk19_q7", imageUrl: "/skills/sk19_p076_04.jpg", text: "مع إبراهيم $120$ ريال من فئتي ( $10$ و $5$ ) ريالات ، إذا كان مبلغ فئة الخمسة ريالات ضعف مبلغ فئة العشرة ريال فكم معه من فئة الخمسة ريال؟", choices: ["$20$", "$25$", "$30$", "$80$"], correctIndex: null },
    { id: "sk19_q8", imageUrl: "/skills/sk19_p076_05.jpg", text: "إذا كان $3$ أمثال عمر محمد أقل من عمر والده بثلاث سنوات ، كم سنة عمر والده إذا كان عمره الآن $15$ سنة؟", choices: ["$45$", "$46$", "$48$", "$49$"], correctIndex: null },
    { id: "sk19_q9", imageUrl: "/skills/sk19_p076_06.jpg", text: "عُمر خالد قبل ۳۰ عام رُبع عُمر أحمد، إذا كان عُمر أحمد الآن ٥٠ عاما، ما عُمر خالد الآن؟", choices: ["٣٥", "٣٠", "٢٥", "٢٠"], correctIndex: null },
    { id: "sk19_q10", imageUrl: "/skills/sk19_p077_01.jpg", text: "محمد أكبر من أحمد بسنتين وأحمد أكبر من سعد بسنتين، عمر أحمد عشر سنوات ما مجموع أعمار محمد وأحمد وسعد؟", choices: ["$28$", "$30$", "$32$", "$36$"], correctIndex: null },
    { id: "sk19_q11", imageUrl: "/skills/sk19_p077_02.jpg", text: "مع أحمد ٢٤ ورقة من فئة ١٠ ريال و ٥ ريال، فإذا كان المبلغ من فئة ١٠ ريال أربعة أمثال المبلغ من فئة الـ٥ ريال ، كم المبلغ الذي معه؟", choices: ["٢٤٠", "٢٢٠", "٢٠٠", "١٦٠"], correctIndex: null },
    { id: "sk19_q12", imageUrl: "/skills/sk19_p077_03.jpg", text: "قال أب \"عمري قبل عشر سنوات يساوي أربعة أمثال عُمر ابني، وعُمر ابني بعد سنتين ۲۲ سنة\"، ما عُمر الأب الآن ؟", choices: ["۳۰", "٤٠", "٥٠", "٦٠"], correctIndex: null },
    { id: "sk19_q13", imageUrl: "/skills/sk19_p077_04.jpg", text: "مع شخص $17$ عملة معدنية من فئة الريال والنصف ريال ، فإذا كان المبلغ الإجمالي $15$ ريال ، كم عملة من فئة النصف ريال؟", choices: ["$2$", "$4$", "$8$", "$12$"], correctIndex: null },
    { id: "sk19_q14", imageUrl: "/skills/sk19_p077_05.jpg", text: "إذا كان مع محمد ١٥ ورقة من فئة الريال وضعف ما معه من فئة الريال من فئة ٥ ريال، كم ريال مع محمد ؟", choices: ["٤٥", "١٥٠", "١٦٥", "١٧٥"], correctIndex: null },
    { id: "sk19_q15", imageUrl: "/skills/sk19_p077_06.jpg", text: "مع شخص $20$ ورقة من فئة $5$ ريال و $20$ ريال فإذا كان المبلغ الذي معه $280$ ريال، كم عدد أوراق فئة الـ $20$ ريال؟", choices: ["$10$", "$12$", "$14$", "$16$"], correctIndex: null },
  ] },
  { id: 20, title: "الجذور", questions: [
    { id: "sk20_q2", imageUrl: "/skills/sk20_p082_01.jpg", text: "$\\sqrt{50} - \\sqrt{18} =$", choices: ["$3\\sqrt{3}$", "$\\sqrt{8}$", "$-\\sqrt{8}$", "$2\\sqrt{3}$"], correctIndex: null },
    { id: "sk20_q3", imageUrl: "/skills/sk20_p082_02.jpg", text: "$\\sqrt{19+19+19+…} = 19$ كم مرة تكرر العدد $19$ ؟", choices: ["$19$", "$2$", "$361$", "$18$"], correctIndex: null },
    { id: "sk20_q4", imageUrl: "/skills/sk20_p082_03.jpg", text: "$\\sqrt{\\sqrt{64 \\times 64 \\times 64 \\times 64}} =$", choices: ["$52$", "$62$", "$42$", "$32$"], correctIndex: null },
    { id: "sk20_q5", imageUrl: "/skills/sk20_p082_04.jpg", text: "$\\sqrt[10]{256} =$", choices: ["٤٢", "٨٢", "٠,٤٢", "٠,٨٢"], correctIndex: null },
    { id: "sk20_q6", imageUrl: "/skills/sk20_p082_05.jpg", text: "$\\dfrac{7}{\\sqrt{5}} \\times \\dfrac{5}{\\sqrt{7}} =$", choices: ["$\\sqrt{35}$", "$\\sqrt{12}$", "$\\sqrt{3}$", "$\\sqrt{40}$"], correctIndex: null },
    { id: "sk20_q7", imageUrl: "/skills/sk20_p082_06.jpg", text: "أوجد قيمة $\\dfrac{5\\sqrt{3} + 2\\sqrt{3}}{\\sqrt{3}} =$", choices: ["$5$", "$6$", "$7$", "$8$"], correctIndex: null },
    { id: "sk20_q8", imageUrl: "/skills/sk20_p082_07.jpg", text: "$\\sqrt[3]{0,125}$", choices: ["٠,٢٥", "٠,٥", "١,٢٥", "٢,٢٥"], correctIndex: null },
    { id: "sk20_q9", imageUrl: "/skills/sk20_p083_01.jpg", text: "القيمة التقريبية للعدد $\\sqrt{0{,}17} \\approx$", choices: ["$0{,}3$", "$9$", "$3$", "$1$"], correctIndex: null },
    { id: "sk20_q10", imageUrl: "/skills/sk20_p083_02.jpg", text: "ما أقرب قيمة للمقدار $\\sqrt{9 \\times 3.9}$", choices: ["$5$", "$6$", "$9$", "$7$"], correctIndex: null },
  ] },
  { id: 21, title: "الرسوم البيانية", questions: [
    { id: "sk21_q1", imageUrl: "/skills/sk21_p084_01.jpg", text: "إذا كان عملاء البنك ٢٥٠٠، أوجد عدد العملاء الذين يستخدمون الإنترنت والهاتف المصرفي", choices: ["١٢٠٠", "١٢٥٠", "١٣٠٠", "١٣٥٠"], correctIndex: null },
    { id: "sk21_q2", imageUrl: "/skills/sk21_p084_02.jpg", text: "كم عدد السيارات في الدولة الأكثر إنتاجًا للسيارات؟", choices: ["١٢٠", "١٠٥", "٩٠", "٨٥"], correctIndex: null },
    { id: "sk21_q3", imageUrl: "/skills/sk21_p084_03.jpg", text: "ما نسبة ما يملكه أحمد إلى محمد في الغنم؟", choices: ["$\\dfrac{1}{2}$", "$\\dfrac{1}{3}$", "$\\dfrac{2}{3}$", "$\\dfrac{3}{4}$"], correctIndex: null },
    { id: "sk21_q4", imageUrl: "/skills/sk21_p085_01.jpg", text: "من الرسم يتضح أن إنتاج الأقلام…", choices: ["تناقص ثم تزايد", "تزايد مستمر", "تناقص مستمر", "تزايد ثم تناقص"], correctIndex: null },
    { id: "sk21_q5", imageUrl: "/skills/sk21_p085_02.jpg", text: "ما العام الذي فيه نسبة الواردات إلى الصادرات أكبر ما يمكن؟", choices: ["١٤٣١", "١٤٣٢", "١٤٣٣", "١٤٣٤"], correctIndex: null },
    { id: "sk21_q6", imageUrl: "/skills/sk21_p085_03.jpg", text: "في الشكل المجاور: ما إجمالي الاستهلاك يوم الثلاثاء؟", choices: ["$10$", "$15$", "$25$", "$30$"], correctIndex: null },
    { id: "sk21_q7", imageUrl: "/skills/sk21_p085_04.jpg", text: "ما أكثر حرف يوجد فيه أخطاء؟", choices: ["B", "N", "W", "R"], correctIndex: null },
    { id: "sk21_q8", imageUrl: "/skills/sk21_p086_01.jpg", text: "ما الفرق بين أعلى قيمة وأقل قيمة في الملابس؟", choices: ["$10$", "$200$", "$300$", "$400$"], correctIndex: null },
    { id: "sk21_q9", imageUrl: "/skills/sk21_p086_02.jpg", text: "يمثل الشكل المقابل عدد الطلاب بحسب حروف أسمائهم، وكل شكل = ٥ طلاب، فما عدد الطلاب الكلي؟", choices: ["٧", "١٤", "٣٥", "٥٠"], correctIndex: null },
    { id: "sk21_q10", imageUrl: "/skills/sk21_p086_03.jpg", text: "الجدول المجاور يبين مبيعات السيارات في أحد المعارض، ما نسبة السيارات الأمريكية للكل؟", choices: ["$7 : 40$", "$11 : 20$", "$8 : 40$", "$3 : 40$"], correctIndex: null },
    { id: "sk21_q11", imageUrl: "/skills/sk21_p086_04.jpg", text: "ما الأكثر ثباتًا طوال العام؟", choices: ["الإكسسورات", "طابعات", "جوالات", "كمبيوترات"], correctIndex: null },
  ] },
  { id: 22, title: "المسائل اللفظية وزكاة المال", questions: [
    { id: "sk22_q1", imageUrl: "/skills/sk22_p087_01.jpg", text: "حقيبة كتاب قيمتها ٤٨ ريال إذا كان سعر الكتاب نصف سعر الحقيبة أوجد سعر الكتاب؟", choices: ["١٦", "٣٢", "٤٢", "٢١"], correctIndex: null },
    { id: "sk22_q2", imageUrl: "/skills/sk22_p087_02.jpg", text: "شخص لديه قطعة خشب مستطيلة طولها ٢٤ سم يريد تقسيمها إلى ٢٤ قطعة حيث كل قطعة ١ سم، فكم مرة سوف يقطعها ؟", choices: ["١٧", "٢٧", "٢٨", "٢٣"], correctIndex: null },
    { id: "sk22_q3", imageUrl: "/skills/sk22_p087_03.jpg", text: "خرج رجل من بيته الساعة ٦:٢٩ صباحاً ورجع للبيت الساعة ٧:٤٦ صباحاً ، فكم المدة التي قضاها خارج البيت بالدقائق ؟", choices: ["٨٨", "٧٧", "٦٦", "٥٥"], correctIndex: null },
    { id: "sk22_q4", imageUrl: "/skills/sk22_p087_04.jpg", text: "شخص يقوم بكتابة الأرقام من $1$ - $200$ بالضغط على زر لكتابة كل رقم كم مرة سيضغط الشخص على الأزرار علما أنه لا توجد مسافات أو فواصل؟", choices: ["$492$", "$750$", "$450$", "$400$"], correctIndex: null },
    { id: "sk22_q5", imageUrl: "/skills/sk22_p087_05.jpg", text: "اشترى رجل نوعين من الدهانات النوع الأول ۱۸ علبة سعر العلبة ۳۰ ريال، النوع الثاني ۱۲ علبة سعر العلبة ٤٠ ريال، وقام بخلط النوعين ، فكم سعر الدهان المخلوط؟", choices: ["٤٢", "٤٦", "٣٤", "٣٦"], correctIndex: null },
    { id: "sk22_q6", imageUrl: "/skills/sk22_p088_01.jpg", text: "رجل لديه ٨٨٠٠٠ ريال وعنده ٤ بنات و٩ أولاد وزوجة، فإذا كان نصيب الزوجة الثمن والولد مثلي البنت ، كم نصيب البنت الواحدة؟", choices: ["٣٥٠٠", "٣٠٠٠", "٧٥٠٠", "٧٠٠"], correctIndex: null },
    { id: "sk22_q7", imageUrl: "/skills/sk22_p088_02.jpg", text: "إذا تم توزيع ٣٢ قطعة من الكعك على ١٢ طفل بالتساوي، كم قطعة تبقت؟", choices: ["١٠", "٩", "٨", "٧"], correctIndex: null },
    { id: "sk22_q8", imageUrl: "/skills/sk22_p088_03.jpg", text: "٥ بيوت في كل منهم ٥ أقفاص وكل قفص بداخله ٥ عصافير إذا كان كل عصفور يأكل ٥ حبات قمح، كم عدد حبوب القمح التي يتناولونها؟", choices: ["٧٧٥", "١٢٥", "٢٢٥", "٦٢٥"], correctIndex: null },
    { id: "sk22_q9", imageUrl: "/skills/sk22_p088_04.jpg", text: "مدرسة بها $3$ صفوف يراد اختيار طالب واحد من الطلاب الثلاثة الأوائل بكل صف لتشكيل فريق للطلاب المتفوقين ، بكم طريقة يمكن تكوين الفريق؟", choices: ["$81$", "$54$", "$27$", "$9$"], correctIndex: null },
    { id: "sk22_q10", imageUrl: "/skills/sk22_p088_05.jpg", text: "اشترك شخص بباقة جوال بـ ٤٢ ريال شهرياً ويحاسب الدقيقة الزائدة أو جزء منها بعد انتهاء الباقة بـ ٣٠ هللة فإذا وصلت فاتورته الشهرية ١٧٧ ريال، كم عدد الدقائق الزائدة في هذا الشهر؟", choices: ["٤٤٨", "٤٥٠", "٤٤٦", "٤٤٥"], correctIndex: null },
    { id: "sk22_q11", imageUrl: "/skills/sk22_p088_06.jpg", text: "طابور فيه ٣٠ طالب أمام أحمد ١٠ طلاب وخلف خالد ١٠ طلاب، كم طالب بين أحمد وخالد ؟", choices: ["٦", "٨", "١٠", "١٢"], correctIndex: null },
    { id: "sk22_q12", imageUrl: "/skills/sk22_p089_01.jpg", text: "طابعة تطبع كتاب من صفحة $1$ وطبعت $258$ رقم في ترقيم صفحات الكتاب، كم عدد صفحات الكتاب ؟", choices: ["$121$", "$122$", "$123$", "$124$"], correctIndex: null },
    { id: "sk22_q13", imageUrl: "/skills/sk22_p089_02.jpg", text: "ما هو العدد الذي إذا أضيف إليه مثله ونصفه وربعه يصبح $66$؟", choices: ["$24$", "$30$", "$36$", "$42$"], correctIndex: null },
    { id: "sk22_q14", imageUrl: "/skills/sk22_p089_03.jpg", text: "شخص لديه $4000$ ريال، ما مقدار الزكاة الواجبة عليه ؟", choices: ["$1000$", "$100$", "$10$", "$40$"], correctIndex: null },
    { id: "sk22_q15", imageUrl: "/skills/sk22_p089_04.jpg", text: "إذا كان لدينا الأعداد (٢، ٤، ٥، ٦، ٩) فكم مرة نستطيع تكوين عدد مكون من رقمين مختلفين؟", choices: ["٢٠", "١٦", "١٠", "٢٤"], correctIndex: null },
  ] },
  { id: 23, title: "المعين والمتوازي", questions: [
    { id: "sk23_q1", imageUrl: "/skills/sk23_p090_01.jpg", text: "معين أقطاره $6$ سم , $8$ سم أوجد مساحته", choices: ["$22$", "$48$", "$24$", "$108$"], correctIndex: null },
    { id: "sk23_q2", imageUrl: "/skills/sk23_p090_02.jpg", text: "معين طولا قطريه $8$ سم ، $6$ سم احسب محيطه", choices: ["$24$", "$20$", "$12$", "$15$"], correctIndex: null },
    { id: "sk23_q4", imageUrl: "/skills/sk23_p090_04.jpg", text: "أوجد محيط شبه المنحرف", choices: ["$11.5$", "$10$", "$11$", "$12$"], correctIndex: null },
    { id: "sk23_q5", imageUrl: "/skills/sk23_p091_01.jpg", text: "الشكل مربع ، طول ضلعه = $6$ ، بداخله مثلث ومعين.\nقارن بين:\nالقيمة الأولى: مساحة المثلث\nالقيمة الثانية: مساحة المعين", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk23_q6", imageUrl: "/skills/sk23_p091_02.jpg", text: "أحسب مساحة المعين", choices: ["$3$", "$4$", "$5$", "$6$"], correctIndex: null },
    { id: "sk23_q7", imageUrl: "/skills/sk23_p091_03.jpg", text: "إذا كانت مساحة متوازي الأضلاع = $72$ سم$^2$\nأوجد مساحة المستطيل", choices: ["$48$", "$24$", "$26$", "$12$"], correctIndex: null },
    { id: "sk23_q8", imageUrl: "/skills/sk23_p091_04.jpg", text: "أ ب ج د متوازي أضلاع د هـ = $2$ هـ ج\nأوجد نسبة مساحة المثلث إلي متوازي الأضلاع", choices: ["$1 : 2$", "$6 : 1$", "$3 : 2$", "$1 : 4$"], correctIndex: null },
    { id: "sk23_q9", imageUrl: "/skills/sk23_p092_01.jpg", text: "إذا كان الشكل مربع\nأوجد مساحة الجزء المظلل", choices: ["$12$", "$24$", "$30$", "$36$"], correctIndex: null },
    { id: "sk23_q10", imageUrl: "/skills/sk23_p092_02.jpg", text: "الشكل المجاور مربع أوجد مساحة المظلل", choices: ["$10$", "$8$", "$5$", "$12$"], correctIndex: null },
    { id: "sk23_q11", imageUrl: "/skills/sk23_p092_03.jpg", text: "ما قيمة ص؟", choices: ["٤٠", "٨٠", "١٠٠", "١٤٠"], correctIndex: null },
    { id: "sk23_q12", imageUrl: "/skills/sk23_p092_04.jpg", text: "أوجد مساحة الجزء المظلل", choices: ["١٩", "٣٥", "٧٠", "٧٢"], correctIndex: null },
  ] },
  { id: 24, title: "استبدال المتغيرات", questions: [
    { id: "sk24_q1", imageUrl: "/skills/sk24_p093_01.jpg", text: "قارن بين:\nالقيمة الأولى: $\\text{أ}^2 + \\text{ب}^2$\nالقيمة الثانية: $(\\text{أ} + \\text{ب})^2$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk24_q2", imageUrl: "/skills/sk24_p093_02.jpg", text: "إذا كان : $3 < \\text{أ} < 7$ ، $2 < \\text{ب} < 6$ فأي الآتي خاطئ؟", choices: ["$\\text{أ} \\times \\text{ب} < 42$", "$\\text{أ} + \\text{ب} > 5$", "$\\text{أ} \\times \\text{ب} = 32$", "$\\text{أ} + \\text{ب} < 13$"], correctIndex: null },
    { id: "sk24_q4", imageUrl: "/skills/sk24_p094_02.jpg", text: "إذا كان ل، م، ع أعداد طبيعية مختلفة مرتبة تصاعديا، ل $\\times$ م $\\times$ ع = $77$\nأوجد $\\text{ع}^2 \\times \\text{ل}^2 - \\text{م}^2$", choices: ["$80$", "$77$", "$75$", "$72$"], correctIndex: null },
    { id: "sk24_q5", imageUrl: "/skills/sk24_p094_03.jpg", text: "إذا كان س عدد فردي ، ص عدد زوجي ، ع عدد أولي ، فإن ناتج ٦ ع (٣س+٤ص)", choices: ["عدد زوجي", "عدد فردي", "عدد أولي", "غير ذلك"], correctIndex: null },
    { id: "sk24_q6", imageUrl: "/skills/sk24_p094_04.jpg", text: "إذا كانت م ، ن ، ل أعداد فردية ، فأي من التالي ليس زوجي؟", choices: ["ن - م", "ن + م + 1", "ن + 1", "ن + م + ل - 11"], correctIndex: null },
    { id: "sk24_q7", imageUrl: "/skills/sk24_p094_05.jpg", text: "إذا كان أ > ب > صفر ، قارن بين:\nالقيمة الأولى: $\\sqrt{\\text{أ}}$\nالقيمة الثانية: $\\sqrt{\\text{أ ب}}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk24_q8", imageUrl: "/skills/sk24_p095_01.jpg", text: "إذا كانت $\\text{س}$، $\\text{ص}$، $\\text{ع}$ أعداد صحيحة موجبة،\n$\\text{س} + \\text{ص} + \\text{ع} = 8$ ، $\\text{س} = \\text{ص}$\nقارن بين:\nالقيمة الأولى: $5$\nالقيمة الثانية: $\\text{س}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk24_q9", imageUrl: "/skills/sk24_p095_02.jpg", text: "س عدد فردي ، ص عدد زوجي فأي مما يلي فردي ؟", choices: ["س + ص", "س ص", "٣ ص - ٢", "٢ س + ص"], correctIndex: null },
    { id: "sk24_q10", imageUrl: "/skills/sk24_p095_03.jpg", text: "إذا كانت $\\text{س} > 2$\nقارن بين:\nالقيمة الأولى: $\\dfrac{1}{\\text{س}}$\nالقيمة الثانية: $\\dfrac{1}{2}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk24_q11", imageUrl: "/skills/sk24_p095_04.jpg", text: "إذا كان $\\text{س} \\neq 0$\nقارن بين:\nالقيمة الأولى: $11\\text{س}$\nالقيمة الثانية: $13\\text{س}$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
  ] },
  { id: 25, title: "الدائرة", questions: [
    { id: "sk25_q1", imageUrl: "/skills/sk25_p099_01.jpg", text: "دائرة مساحتها $3,14$ سم$^2$ فإن محيطها بالسم هو", choices: ["$3,14$ سم", "$314$ سم", "$6,28$ سم", "$15,7$ سم"], correctIndex: null },
    { id: "sk25_q2", imageUrl: "/skills/sk25_p099_02.jpg", text: "إذا علمت أن أ ب قطر الدائرة ، احسب محيط الدائرة", choices: ["٣٫١٤", "٣١٤", "٦٫٢٨", "١٥٫٧"], correctIndex: null },
    { id: "sk25_q3", imageUrl: "/skills/sk25_p099_03.jpg", text: "مربع طول ضلعه $10$ سم مرسوم داخل دائرة احسب مساحة الدائرة", choices: ["$25$ ط $\\text{سم}^2$", "$50$ ط $\\text{سم}^2$", "$100$ ط $\\text{سم}^2$", "$75$ ط $\\text{سم}^2$"], correctIndex: null },
    { id: "sk25_q4", imageUrl: "/skills/sk25_p099_04.jpg", text: "مساحة الدائرة التي معادلتها $\\dfrac{1}{2} \\text{س}^2 + \\dfrac{1}{2} \\text{ص}^2 = 18$", choices: ["$81$ ط", "$18$ ط", "$36$ ط", "$75$ ط"], correctIndex: null },
    { id: "sk25_q5", imageUrl: "/skills/sk25_p099_05.jpg", text: "أوجد مساحة أكبر دائرة يمكن رسمها داخل مربع طول ضلعه = $8$ سم", choices: ["$64$ ط $\\text{سم}^2$", "$14$ ط $\\text{سم}^2$", "$8$ ط $\\text{سم}^2$", "$16$ ط $\\text{سم}^2$"], correctIndex: null },
    { id: "sk25_q6", imageUrl: "/skills/sk25_p099_06.jpg", text: "أوجد مساحة المظلل", choices: ["$64 - 16\\text{ط}$", "$16\\text{ط} - 64$", "$64 - 8\\text{ط}$", "$16\\text{ط} - 16$"], correctIndex: null },
    { id: "sk25_q7", imageUrl: "/skills/sk25_p100_01.jpg", text: "أوجد مساحة المظلل", choices: ["١٦ - ٤ط", "٤ - ١٦ط", "١٦ط - ١٦", "١٦ط - ٤"], correctIndex: null },
    { id: "sk25_q8", imageUrl: "/skills/sk25_p100_02.jpg", text: "الدائرتين متطابقتين أوجد مساحة الدائرة", choices: ["$2$ ط", "$4$ ط", "$16$ ط", "ط"], correctIndex: null },
    { id: "sk25_q9", imageUrl: "/skills/sk25_p100_03.jpg", text: "إذا كانت الدائرتان متطابقتان احسب محيط الدائرة الواحدة", choices: ["16 ط", "4 ط", "36 ط", "25 ط"], correctIndex: null },
    { id: "sk25_q10", imageUrl: "/skills/sk25_p100_04.jpg", text: "إذا كانت الدوائر متطابقة وطول ضلع المربع = $8$\nاحسب مساحة الدائرة", choices: ["$8$ ط", "$4$ ط", "$12$ ط", "$18$ ط"], correctIndex: null },
    { id: "sk25_q11", imageUrl: "/skills/sk25_p100_05.jpg", text: "احسب مساحة الجزء المظلل", choices: ["$64 - 16\\text{ط}$", "$16\\text{ط} - 64$", "$64\\text{ط} - 16$", "$16\\text{ط} - 16$"], correctIndex: null },
    { id: "sk25_q12", imageUrl: "/skills/sk25_p101_01.jpg", text: "احسب مساحة الدائرة الكبرى", choices: ["$36\\text{ ط}$", "$3\\text{ ط}$", "$81\\text{ ط}$", "$9\\text{ ط}$"], correctIndex: null },
    { id: "sk25_q13", imageUrl: "/skills/sk25_p101_02.jpg", text: "دائرة نصف قطرها $100$ سم ، رسم على قطرها $20$ دائرة متطابقة ، احسب نسبة محيط الدائرة الصغيرة إلى محيط الدائرة الكبيرة ؟", choices: ["$\\dfrac{1}{10}$", "$\\dfrac{1}{100}$", "$\\dfrac{1}{20}$", "$\\dfrac{1}{400}$"], correctIndex: null },
    { id: "sk25_q14", imageUrl: "/skills/sk25_p101_03.jpg", text: "دائرة نصف قطرها $100$ سم ، رسم على قطرها $10$ دوائر متطابقة ، احسب نسبة مساحة الدائرة الصغيرة إلى مساحة الدائرة الكبيرة", choices: ["$\\dfrac{1}{10}$", "$\\dfrac{1}{100}$", "$\\dfrac{1}{20}$", "$\\dfrac{1}{400}$"], correctIndex: null },
  ] },
  { id: 26, title: "المساحات المظللة", questions: [
    { id: "sk26_q1", imageUrl: "/skills/sk26_p103_01.jpg", text: "في الشكل المرسوم ثلاث مربعات كل مربع صغير مرسوم من منتصف أضلاع الأكبر منه إذا كان طول ضلع الصغير $2$ احسب مساحة الكبير", choices: ["$4$", "$8$", "$16$", "$20$"], correctIndex: null },
    { id: "sk26_q2", imageUrl: "/skills/sk26_p103_02.jpg", text: "إذا كانت المثلثات جميعها متطابقة الأضلاع وكل مثلث مرسوم من منتصف أضلاع الأكبر وإذا كانت مساحة الكبير $64$ احسب مساحة المظلل", choices: ["$2$", "$4$", "$8$", "$12$"], correctIndex: null },
    { id: "sk26_q3", imageUrl: "/skills/sk26_p103_03.jpg", text: "الشكل مربع طول ضلعه = $4$ احسب مساحة المظلل", choices: ["$10$", "$12$", "$16$", "$8$"], correctIndex: null },
    { id: "sk26_q4", imageUrl: "/skills/sk26_p103_04.jpg", text: "مساحة الجزء المظلل", choices: ["$24$", "$35$", "$29$", "$18$"], correctIndex: null },
    { id: "sk26_q5", imageUrl: "/skills/sk26_p104_01.jpg", text: "ما نسبة مساحة المظلل إلى مساحة المستطيل ؟", choices: ["$2 : 1$", "$1 : 2$", "$3 : 1$", "$4 : 1$"], correctIndex: null },
    { id: "sk26_q6", imageUrl: "/skills/sk26_p104_02.jpg", text: "إذا كان الشكل مربع\nأوجد مساحة الجزء المظلل", choices: ["$12$", "$16$", "$24$", "$28$"], correctIndex: null },
    { id: "sk26_q7", imageUrl: "/skills/sk26_p104_03.jpg", text: "احسب مساحة الجزء المظلل", choices: ["$25$", "$36$", "$24$", "$49$"], correctIndex: null },
    { id: "sk26_q8", imageUrl: "/skills/sk26_p105_01.jpg", text: "مساحة الشكل المظلل", choices: ["$3$", "$6$", "$7$", "$9$"], correctIndex: null },
    { id: "sk26_q9", imageUrl: "/skills/sk26_p105_02.jpg", text: "أوجد محيط الشكل", choices: ["$18$", "$20$", "$30$", "$36$"], correctIndex: null },
  ] },
  { id: 27, title: "النسبة والتناسب", questions: [
    { id: "sk27_q2", imageUrl: "/skills/sk27_p109_01.jpg", text: "مدرسة بها $210$ طالب منهم $70$ طالب في الصف الأول، أوجد نسبة طلاب الصف الأول إلى باقي طلاب المدرسة", choices: ["$1 : 3$", "$1 : 2$", "$2 : 3$", "$1 : 4$"], correctIndex: null },
    { id: "sk27_q3", imageUrl: "/skills/sk27_p109_02.jpg", text: "ما نسبة المظلل إلى الشكل كاملاً", choices: ["$3 : 2$", "$2 : 1$", "$2 : 3$", "$3 : 1$"], correctIndex: null },
    { id: "sk27_q4", imageUrl: "/skills/sk27_p109_03.jpg", text: "مدرسة بها ۱۲۰ طالب غاب منهم ٤٠ طالب ،ما النسبة المئوية للحضور تقريباً ؟", choices: ["٤٠٪", "٥٠٪", "٦٧٪", "٧٥٪"], correctIndex: null },
    { id: "sk27_q5", imageUrl: "/skills/sk27_p109_04.jpg", text: "إذا كانت نسبة المتفوقين لغيرهم $1 : 4$ فما نسبتهم المئوية ؟", choices: ["%٢٠", "%٢٥", "%٤٠", "%٣٣"], correctIndex: null },
    { id: "sk27_q6", imageUrl: "/skills/sk27_p110_01.jpg", text: "ما قيمة $10\\%$ من العدد $450$ :", choices: ["$30$", "$40$", "$45$", "$50$"], correctIndex: null },
    { id: "sk27_q7", imageUrl: "/skills/sk27_p110_02.jpg", text: "باع رجل تلفاز بمبلغ $2400$ ريال وقد ربح فيه $20\\%$ فبكم اشتراه ؟", choices: ["$1800$", "$2000$", "$2200$", "$2300$"], correctIndex: null },
    { id: "sk27_q8", imageUrl: "/skills/sk27_p110_03.jpg", text: "زاد سعر سلعة بنسبة $20\\%$ في السنة الأولى ثم زادت بنسبة $5\\%$ في السنة الثانية فما نسبة الزيادة في السعر خلال السنتين ؟", choices: ["$10\\%$", "$16\\%$", "$25\\%$", "$26\\%$"], correctIndex: null },
    { id: "sk27_q9", imageUrl: "/skills/sk27_p110_04.jpg", text: "مربع جعلنا طول ضلعه ثلاثة أمثاله ، ما النسبة المئوية للزيادة في مساحته ؟", choices: ["$800\\%$", "$600\\%$", "$300\\%$", "$400\\%$"], correctIndex: null },
    { id: "sk27_q10", imageUrl: "/skills/sk27_p110_05.jpg", text: "تكتب فاطمة ١٦ كلمة في ٢٠ ثانية، فكم تكتب في ٤٥ ثانية؟", choices: ["٣٢", "٣٦", "٣٧", "٣٨"], correctIndex: null },
    { id: "sk27_q11", imageUrl: "/skills/sk27_p110_06.jpg", text: "يستطيع ٣ عمال إنجاز عمل ما في ١٢ يوم كم يستغرق ٩ عمال لإنجاز هذا العمل؟", choices: ["٤", "٥", "٦", "٧"], correctIndex: null },
    { id: "sk27_q12", imageUrl: "/skills/sk27_p111_01.jpg", text: "إذا زرع مزارع ٣٠٠ فسيله في ٦٠ يوم ، فكم يوم يحتاج ١٠ عمال لزراعة نفس العدد من الفسائل؟", choices: ["١٠", "٨", "٦", "١٣"], correctIndex: null },
    { id: "sk27_q13", imageUrl: "/skills/sk27_p111_02.jpg", text: "عمر محمد نصف عمر سعد وعمر سعد ثلاث أضعاف عمر فهد\nما نسبة عمر محمد إلى عمر فهد؟", choices: ["$2 : 3$", "$3 : 2$", "$1 : 3$", "$4 : 1$"], correctIndex: null },
  ] },
  { id: 28, title: "المجسمات", questions: [
    { id: "sk28_q1", imageUrl: "/skills/sk28_p113_01.jpg", text: "خزان على شكل متوازي مستطيلات ابعاده $2$ م , $6$ م , $\\dfrac{1}{2}$ م فما حجمه؟", choices: ["$2$ م$^3$", "$4$ م$^3$", "$6$ م$^3$", "$8$ م$^3$"], correctIndex: null },
    { id: "sk28_q2", imageUrl: "/skills/sk28_p113_02.jpg", text: "خزان ماء مكعب الشكل طول حرفه $6$ م ، كم يبلغ حجمه ؟", choices: ["$216$ م$^2$", "$36$ م$^2$", "$72$ م$^2$", "$96$ م$^2$"], correctIndex: null },
    { id: "sk28_q4", imageUrl: "/skills/sk28_p113_04.jpg", text: "مكعب مساحة أوجهه $864$ م$^2$ ، كم طول حرفه ؟", choices: ["$11$", "$10$", "$12$", "$14$"], correctIndex: null },
    { id: "sk28_q5", imageUrl: "/skills/sk28_p113_05.jpg", text: "كم يبلغ حجم أسطوانة نصف قطر قاعدتها $10$ سم وارتفاعها $10$ سم", choices: ["$1000$ ط $\\text{سم}^3$", "$100$ ط $\\text{سم}^3$", "$20$ ط $\\text{سم}^3$", "$1$ ط $\\text{سم}^3$"], correctIndex: null },
    { id: "sk28_q6", imageUrl: "/skills/sk28_p113_06.jpg", text: "مسبح مربع الشكل كم متر مكعب سعة المسبح تقريبا؟", choices: ["$9\\text{ م}^3$", "$10\\text{ م}^3$", "$16\\text{ م}^3$", "$25\\text{ م}^3$"], correctIndex: null },
    { id: "sk28_q7", imageUrl: "/skills/sk28_p114_01.jpg", text: "ما نسبة حجم مكعب حرفه ٢ سم إلى حجم مكعب طول حرفه ٤سم ؟", choices: ["$1:2 \\text{ سم}^3$", "$1:4 \\text{ سم}^3$", "$1:8 \\text{ سم}^3$", "$1:16 \\text{ سم}^3$"], correctIndex: null },
    { id: "sk28_q8", imageUrl: "/skills/sk28_p114_02.jpg", text: "أسطوانة ارتفاعها يساوي ضعف طول نصف قطر قاعدتها\nقارن بين:\nالقيمة الأولى: ارتفاعها\nالقيمة الثانية: محيط قاعدتها", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk28_q9", imageUrl: "/skills/sk28_p114_03.jpg", text: "قارن بين:\nالقيمة الأولى: كمية العصير\nالقيمة الثانية: $750$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk28_q10", imageUrl: "/skills/sk28_p114_04.jpg", text: "أسطوانة مساحة قاعدتها $15$ م$^2$، وارتفاعها $15$ م، كم نحتاج من الماء لملء ثلث الأسطوانة؟", choices: ["$60$ م$^3$", "$75$ م$^3$", "$120$ م$^3$", "$150$ م$^3$"], correctIndex: null },
    { id: "sk28_q11", imageUrl: "/skills/sk28_p114_05.jpg", text: "إذا كان هناك إناءان الأول أكبر حجمًا من الثاني ،\nقارن بين\nالقيمة الأولى: مساحة سطح الأول\nالقيمة الثانية: مساحة سطح الثاني", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk28_q12", imageUrl: "/skills/sk28_p115_01.jpg", text: "مكعب حجمه $125\\text{ سم}^3$، احسب مساحته؟", choices: ["$25\\text{ سم}^2$", "$250\\text{ سم}^2$", "$150\\text{ سم}^2$", "$30\\text{ سم}^2$"], correctIndex: null },
    { id: "sk28_q13", imageUrl: "/skills/sk28_p115_02.jpg", text: "أسطوانة دائرية قائمة طول قطر قاعدتها = $8$ سم وارتفاعها = $5$ سم ، احسب حجم الأسطوانة.", choices: ["$63$ ط سم$^3$", "$72$ ط سم$^3$", "$40$ ط سم$^3$", "$32$ ط سم$^3$"], correctIndex: null },
    { id: "sk28_q14", imageUrl: "/skills/sk28_p115_03.jpg", text: "هدية علي شكل مكعب مغلفة بغلاف فإذا هناك شريط حول حواف الهدية طوله = $120$ سم، ما مساحة الغلاف ؟", choices: ["$600$ سم$^2$", "$480$ سم$^2$", "$400$ سم$^2$", "$200$ سم$^2$"], correctIndex: null },
    { id: "sk28_q15", imageUrl: "/skills/sk28_p115_04.jpg", text: "ما مساحة أوجه متوازي مستطيلات أبعاده $2$ سم ، $2$ سم ، $5$ سم", choices: ["$30$ سم$^2$", "$62$ سم$^2$", "$48$ سم$^2$", "$96$ سم$^2$"], correctIndex: null },
  ] },
  { id: 29, title: "المثلثان المتشابهان", questions: [
    { id: "sk29_q1", imageUrl: "/skills/sk29_p116_01.jpg", text: "في الشكل المجاور : أوجد قيمة س ؟", choices: ["$1{,}4$", "$1{,}6$", "$1{,}8$", "$2$"], correctIndex: null },
    { id: "sk29_q2", imageUrl: "/skills/sk29_p116_02.jpg", text: "أوجد قيمة س على الرسم؟", choices: ["$4$", "$5$", "$9$", "$20$"], correctIndex: null },
    { id: "sk29_q3", imageUrl: "/skills/sk29_p116_03.jpg", text: "إذا كان المثلثان متشابهان\nأوجد طول الضلع $\\overline{\\text{أ ج}}$", choices: ["$10$", "$12$", "$20$", "$24$"], correctIndex: null },
    { id: "sk29_q4", imageUrl: "/skills/sk29_p117_01.jpg", text: "أوجد طول الضلع أ ب", choices: ["٦", "١٢", "٢٤", "٣٢"], correctIndex: null },
    { id: "sk29_q5", imageUrl: "/skills/sk29_p117_02.jpg", text: "أوجد طول ب د ؟", choices: ["٥", "٤", "٣", "٢"], correctIndex: null },
    { id: "sk29_q6", imageUrl: "/skills/sk29_p117_03.jpg", text: "أوجد قيمة س ؟", choices: ["$5$", "$6$", "$7$", "$8$"], correctIndex: null },
    { id: "sk29_q7", imageUrl: "/skills/sk29_p117_04.jpg", text: "في الشكل المقابل ما المستطيل المشابه للمستطيل أ د هـ ز", choices: ["أ ب ك ز", "ب ج و ك", "ن ح ز ي", "أ د ط ح"], correctIndex: null },
    { id: "sk29_q8", imageUrl: "/skills/sk29_p118_01.jpg", text: "أوجد قيمة س ؟", choices: ["$40$", "$50$", "$60$", "$70$"], correctIndex: null },
    { id: "sk29_q9", imageUrl: "/skills/sk29_p118_02.jpg", text: "أ ب ج د متوازي أضلاع ،\nأوجد نسبة د م : م ب", choices: ["$\\dfrac{2}{3}$", "$\\dfrac{4}{5}$", "$\\dfrac{5}{6}$", "$\\dfrac{1}{3}$"], correctIndex: null },
    { id: "sk29_q10", imageUrl: "/skills/sk29_p118_03.jpg", text: "إذا كان أ ج = $5$ سم ، ب ج = $4$ سم ،\nأوجد طول د هـ", choices: ["$1.5$", "$2.5$", "$2$", "$3$"], correctIndex: null },
    { id: "sk29_q11", imageUrl: "/skills/sk29_p118_04.jpg", text: "أوجد قيمة س ؟", choices: ["$18$", "$16$", "$20$", "$22$"], correctIndex: null },
  ] },
  { id: 30, title: "إتقان الكمي", questions: [
    { id: "sk30_q2", imageUrl: "/skills/sk30_p119_02.jpg", text: "قارن بين:\nالقيمة الأولى: $5959 \\times 5959$\nالقيمة الثانية: $6060 \\div 60$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk30_q3", imageUrl: "/skills/sk30_p119_03.jpg", text: "تتابع مريم متوسط درجاتها، فإذا اختبرت $3$ اختبارات وإذا حصلت مريم على $11$ درجة في الاختبار التالي سيزيد متوسط درجاتها $1$، وإذا حصلت على $11$ في كل اختبار من الاختبارات الثلاثة التالية فسيزيد متوسط درجاتها $2$، ما هو متوسط درجات اختباراتها حاليًا؟", choices: ["$4$", "$5$", "$6$", "$7$"], correctIndex: null },
    { id: "sk30_q4", imageUrl: "/skills/sk30_p119_04.jpg", text: "أوجد قيمة س", choices: ["٤", "٦", "٨", "١٠"], correctIndex: null },
    { id: "sk30_q5", imageUrl: "/skills/sk30_p119_05.jpg", text: "فاز فريق بـ $60\\%$ من المباريات التي لعبها ، وتبقي له $15$ مباراة ويريد الفوز بـ $60\\%$ من إجمالي المباريات كم مباراة يمكن أن يخسرها من المباريات المتبقية؟", choices: ["$6$", "$7$", "$8$", "$9$"], correctIndex: null },
    { id: "sk30_q7", imageUrl: "/skills/sk30_p120_02.jpg", text: "قارن بين:\nالقيمة الأولى: $\\text{س}^2$\nالقيمة الثانية: $15$", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
    { id: "sk30_q8", imageUrl: "/skills/sk30_p120_03.jpg", text: "يخرج شخص من منزله يوميا الساعة ٧ ليصل إلى عمله على موعد الحضور بالضبط ٧:٣٠ ، وإذا تأخر ٤ دقائق تحسب عليه ١٠ دقائق تأخير ، إذا خرج في أحد الأيام الساعة ٧:١٠ ، فمتى يتم تسجيل حضوره في هذا اليوم ؟", choices: ["٧:٣٥", "٧:٤٥", "٧:٥٥", "٨:٠٥"], correctIndex: null },
    { id: "sk30_q9", imageUrl: "/skills/sk30_p120_04.jpg", text: "إذا كان المثلث متطابق الأضلاع وطول ضلعه $12$ سم، فما مساحة الجزء المظلل ؟", choices: ["$2\\text{ط} - 12\\sqrt{3}$", "$16\\text{ط} + 12\\sqrt{3}$", "$2\\text{ط} + 12\\sqrt{3}$", "$4\\text{ط} - 12\\sqrt{3}$"], correctIndex: null },
    { id: "sk30_q10", imageUrl: "/skills/sk30_p120_05.jpg", text: "كم عدد طرق جلوس أب وأم وخالة و 3 أبناء على طاولة دائرة بحيث يجلس الأب تحت المكيف؟", choices: ["$120$", "$180$", "$240$", "$720$"], correctIndex: null },
    { id: "sk30_q11", imageUrl: "/skills/sk30_p120_06.jpg", text: "احسب مساحة الجزء المظلل", choices: ["$114$", "$57$", "$28.5$", "$14.25$"], correctIndex: null },
    { id: "sk30_q12", imageUrl: "/skills/sk30_p121_01.jpg", text: "اسطوانة زاد طول نصف قطرها إلي الضعف ، كم مرة زاد حجمها :", choices: ["مرة", "مرتين", "٣ مرات", "٤ مرات"], correctIndex: null },
    { id: "sk30_q13", imageUrl: "/skills/sk30_p121_02.jpg", text: "إذا كان مساحة الدائرة = مساحة سداسي منتظم = $16\\text{ سم}^2$ ، قارن بين:\nالقيمة الأولى: محيط الدائرة\nالقيمة الثانية: محيط السداسي", choices: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctIndex: null },
  ] },
];

export function getSkill(id: number): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}

export const SKILL_SECONDS_PER_QUESTION = 60;
export const SKILL_RESULTS_KEY = "nemr:results:skills";
